<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>5 Zwevend stof - Fysisch-chemische parameters | Concept Eerstelijnsrapportage Westerschelde (IN ONTWIKKELING)</title>
  <meta name="description" content="5 Zwevend stof - Fysisch-chemische parameters | Concept Eerstelijnsrapportage Westerschelde (IN ONTWIKKELING)" />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="5 Zwevend stof - Fysisch-chemische parameters | Concept Eerstelijnsrapportage Westerschelde (IN ONTWIKKELING)" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="5 Zwevend stof - Fysisch-chemische parameters | Concept Eerstelijnsrapportage Westerschelde (IN ONTWIKKELING)" />
  
  
  

<meta name="author" content="Deltares" />


<meta name="date" content="2022-02-17" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="fysisch-oppwater.html"/>
<link rel="next" href="bodem.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.5.1/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-1.3.1/leaflet.js"></script>
<link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="libs/proj4-2.6.2/proj4.min.js"></script>
<script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding-2.0.4.1/leaflet.js"></script>
<script src="libs/plotly-binding-4.10.0/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.5.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.5.1/plotly-latest.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

<style>
.zoomDiv {
  opacity: 0;
  position:absolute;
  top: 50%;
  left: 50%;
  z-index: 50;
  transform: translate(-50%, -50%);
  box-shadow: 0px 0px 50px #888888;
  max-height:100%; 
  overflow: scroll;
}

.zoomImg {
  width: 100%;
}
</style>


<script type="text/javascript">
  $(document).ready(function() {
    $('body').prepend("<div class=\"zoomDiv\"><img src=\"\" class=\"zoomImg\"></div>");
    // onClick function for all plots (img's)
    $('img:not(.zoomImg):not(.logo)').click(function() {
      $('.zoomImg').attr('src', $(this).attr('src'));
      $('.zoomDiv').css({opacity: '1', width: '60%'});
    });
    // onClick function for zoomImg
    $('img.zoomImg').click(function() {
      $('.zoomDiv').css({opacity: '0', width: '0%'});
    });
  });
</script>




<link rel="stylesheet" href="navbar/navbar.css" type="text/css" />
<link rel="stylesheet" href="style/deltares.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Voorwoord</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#samenvatting"><i class="fa fa-check"></i><b>1.1</b> Samenvatting</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#rapportversie"><i class="fa fa-check"></i><b>1.2</b> Versie</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="inleiding.html"><a href="inleiding.html"><i class="fa fa-check"></i><b>2</b> Inleiding</a>
<ul>
<li class="chapter" data-level="2.1" data-path="inleiding.html"><a href="inleiding.html#achtergrond"><i class="fa fa-check"></i><b>2.1</b> Achtergrond</a></li>
<li class="chapter" data-level="2.2" data-path="inleiding.html"><a href="inleiding.html#doelstelling"><i class="fa fa-check"></i><b>2.2</b> Doelstelling</a></li>
<li class="chapter" data-level="2.3" data-path="inleiding.html"><a href="inleiding.html#verwerkte-data"><i class="fa fa-check"></i><b>2.3</b> Verwerkte data</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="inleiding.html"><a href="inleiding.html#ontbrekende-data"><i class="fa fa-check"></i><b>2.3.1</b> Ontbrekende data</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="inleiding.html"><a href="inleiding.html#leeswijzer"><i class="fa fa-check"></i><b>2.4</b> Leeswijzer</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="hydro.html"><a href="hydro.html"><i class="fa fa-check"></i><b>3</b> Hydrodynamiek</a>
<ul>
<li class="chapter" data-level="3.1" data-path="hydro.html"><a href="hydro.html#waterstanden"><i class="fa fa-check"></i><b>3.1</b> Waterstanden</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="hydro.html"><a href="hydro.html#hydroInfoMeting"><i class="fa fa-check"></i><b>3.1.1</b> Informatie over de metingen</a></li>
<li class="chapter" data-level="3.1.2" data-path="hydro.html"><a href="hydro.html#hydroHWLW"><i class="fa fa-check"></i><b>3.1.2</b> Jaargemiddelde hoog- en laagwaterstanden</a></li>
<li class="chapter" data-level="3.1.3" data-path="hydro.html"><a href="hydro.html#hydroGetijslag"><i class="fa fa-check"></i><b>3.1.3</b> Jaargemiddelde getijslag</a></li>
<li class="chapter" data-level="3.1.4" data-path="hydro.html"><a href="hydro.html#hydroGetijcomponenten"><i class="fa fa-check"></i><b>3.1.4</b> Getijcomponenten</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="hydro.html"><a href="hydro.html#golven"><i class="fa fa-check"></i><b>3.2</b> Golven IN ONTWIKKELING</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="hydro.html"><a href="hydro.html#golvenInfoMeting"><i class="fa fa-check"></i><b>3.2.1</b> Informatie over de metingen</a></li>
<li class="chapter" data-level="3.2.2" data-path="hydro.html"><a href="hydro.html#golvenHoogte"><i class="fa fa-check"></i><b>3.2.2</b> Golfhoogte</a></li>
<li class="chapter" data-level="3.2.3" data-path="hydro.html"><a href="hydro.html#golvenPeriode"><i class="fa fa-check"></i><b>3.2.3</b> Golfperiode</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html"><i class="fa fa-check"></i><b>4</b> Oppervlaktewater - Fysisch-chemische parameters</a>
<ul>
<li class="chapter" data-level="4.1" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#oppInfoMetingen"><i class="fa fa-check"></i><b>4.1</b> Informatie over de metingen</a></li>
<li class="chapter" data-level="4.2" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#saliniteit"><i class="fa fa-check"></i><b>4.2</b> Saliniteit</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#saliniteit-jaargemiddelde"><i class="fa fa-check"></i><b>4.2.1</b> Jaarlijkse waarden</a></li>
<li class="chapter" data-level="4.2.2" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#saliniteit-winterzomer"><i class="fa fa-check"></i><b>4.2.2</b> Zomer- en winterwaarden</a></li>
<li class="chapter" data-level="4.2.3" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#saliniteit-maandgemiddelde"><i class="fa fa-check"></i><b>4.2.3</b> Maandelijkse waarden</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#watertemp"><i class="fa fa-check"></i><b>4.3</b> Watertemperatuur</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#watertemp-jaargemiddelde"><i class="fa fa-check"></i><b>4.3.1</b> Jaarlijkse waarden</a></li>
<li class="chapter" data-level="4.3.2" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#watertemp-winterzomer"><i class="fa fa-check"></i><b>4.3.2</b> Zomer- en de winterwaarden</a></li>
<li class="chapter" data-level="4.3.3" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#watertemp-maandgemiddelde"><i class="fa fa-check"></i><b>4.3.3</b> Maandelijkse waarden</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#zuurstof"><i class="fa fa-check"></i><b>4.4</b> Zuurstof</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#zuurstof-jaar-verzadiging"><i class="fa fa-check"></i><b>4.4.1</b> jaarmediane verzadigingspercentage zuurstof</a></li>
<li class="chapter" data-level="4.4.2" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#zuurstof-jaar-gehalte"><i class="fa fa-check"></i><b>4.4.2</b> jaarmediane zuurstofgehalte</a></li>
<li class="chapter" data-level="4.4.3" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#zuurstof-maand-verzadiging"><i class="fa fa-check"></i><b>4.4.3</b> Maandelijkse waarden verzadigingspercentage zuurstof</a></li>
<li class="chapter" data-level="4.4.4" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#zuurstof-maand-gehalte"><i class="fa fa-check"></i><b>4.4.4</b> Maandelijkse waarden zuurstofgehalte</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#chlorofyl"><i class="fa fa-check"></i><b>4.5</b> Chlorofyl-a</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#chlorofyl-jaar"><i class="fa fa-check"></i><b>4.5.1</b> Jaarlijkse waarden</a></li>
<li class="chapter" data-level="4.5.2" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#chlorofyl-zomerwinter"><i class="fa fa-check"></i><b>4.5.2</b> Zomer- en winterwaardes</a></li>
<li class="chapter" data-level="4.5.3" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#chlorofyl-maand"><i class="fa fa-check"></i><b>4.5.3</b> Maandelijkse waarden</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#feofytine"><i class="fa fa-check"></i><b>4.6</b> Feofytine-a</a></li>
<li class="chapter" data-level="4.7" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#zuurstofverbruik"><i class="fa fa-check"></i><b>4.7</b> Chemisch en biochemisch zuurstofverbruik</a>
<ul>
<li class="chapter" data-level="4.7.1" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#chemisch-zuurstofgebruik"><i class="fa fa-check"></i><b>4.7.1</b> Chemisch zuurstofgebruik</a></li>
<li class="chapter" data-level="4.7.2" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#biochemisch-zuurstofgebruik"><i class="fa fa-check"></i><b>4.7.2</b> Biochemisch zuurstofgebruik</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#lichtklimaat"><i class="fa fa-check"></i><b>4.8</b> Lichtklimaat</a>
<ul>
<li class="chapter" data-level="4.8.1" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#doorzicht"><i class="fa fa-check"></i><b>4.8.1</b> Doorzicht</a></li>
<li class="chapter" data-level="4.8.2" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#extinctiecoef"><i class="fa fa-check"></i><b>4.8.2</b> Extinctiecoefficient</a></li>
</ul></li>
<li class="chapter" data-level="4.9" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#zwevende-stof"><i class="fa fa-check"></i><b>4.9</b> Zwevende stof</a>
<ul>
<li class="chapter" data-level="4.9.1" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#zwevende-stof-jaar"><i class="fa fa-check"></i><b>4.9.1</b> Jaarlijkse waarden</a></li>
<li class="chapter" data-level="4.9.2" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#zwevende-stof-zomerwinter"><i class="fa fa-check"></i><b>4.9.2</b> Gemiddelde waardes in de zomer en de winter</a></li>
<li class="chapter" data-level="4.9.3" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#afwijking-van-het-langjarig-gemiddelde-anomalie"><i class="fa fa-check"></i><b>4.9.3</b> Afwijking van het langjarig gemiddelde (anomalie)</a></li>
</ul></li>
<li class="chapter" data-level="4.10" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#nutrienten"><i class="fa fa-check"></i><b>4.10</b> Nutriënten</a>
<ul>
<li class="chapter" data-level="4.10.1" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#stikstof"><i class="fa fa-check"></i><b>4.10.1</b> Totaal opgelost stikstof</a></li>
<li class="chapter" data-level="4.10.2" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#part-gebonden-stikstof"><i class="fa fa-check"></i><b>4.10.2</b> Particulair gebonden stikstof</a></li>
<li class="chapter" data-level="4.10.3" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#ammonium"><i class="fa fa-check"></i><b>4.10.3</b> Ammonium</a></li>
<li class="chapter" data-level="4.10.4" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#nitriet"><i class="fa fa-check"></i><b>4.10.4</b> Nitriet</a></li>
<li class="chapter" data-level="4.10.5" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#nitraat"><i class="fa fa-check"></i><b>4.10.5</b> Nitraat</a></li>
<li class="chapter" data-level="4.10.6" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#orthofosfaat"><i class="fa fa-check"></i><b>4.10.6</b> Orthofosfaat</a></li>
<li class="chapter" data-level="4.10.7" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#totaal-fosfaat"><i class="fa fa-check"></i><b>4.10.7</b> Totaal opgelost fosfaat</a></li>
<li class="chapter" data-level="4.10.8" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#part-gebonden-fosfaat"><i class="fa fa-check"></i><b>4.10.8</b> Particulair gebonden fosfaat</a></li>
<li class="chapter" data-level="4.10.9" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#silicaat"><i class="fa fa-check"></i><b>4.10.9</b> Silicaat</a></li>
</ul></li>
<li class="chapter" data-level="4.11" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#organisch-koolstof"><i class="fa fa-check"></i><b>4.11</b> Organisch koolstof</a>
<ul>
<li class="chapter" data-level="4.11.1" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#opgelost-organisch-koolstof"><i class="fa fa-check"></i><b>4.11.1</b> Opgelost organisch koolstof</a></li>
<li class="chapter" data-level="4.11.2" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#part-gebonden-organisch-koolstof"><i class="fa fa-check"></i><b>4.11.2</b> Particulair gebonden organisch koolstof</a></li>
</ul></li>
<li class="chapter" data-level="4.12" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#cnp-ratio"><i class="fa fa-check"></i><b>4.12</b> C:N:P ratio’s</a></li>
<li class="chapter" data-level="4.13" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#metalen"><i class="fa fa-check"></i><b>4.13</b> Metalen</a>
<ul>
<li class="chapter" data-level="4.13.1" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#boor"><i class="fa fa-check"></i><b>4.13.1</b> Boor</a></li>
<li class="chapter" data-level="4.13.2" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#boor-fil"><i class="fa fa-check"></i><b>4.13.2</b> Boor na filtratie</a></li>
<li class="chapter" data-level="4.13.3" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#chroom"><i class="fa fa-check"></i><b>4.13.3</b> Chroom</a></li>
<li class="chapter" data-level="4.13.4" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#chroom-fil"><i class="fa fa-check"></i><b>4.13.4</b> Chroom na filtratie</a></li>
<li class="chapter" data-level="4.13.5" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#koper"><i class="fa fa-check"></i><b>4.13.5</b> Koper</a></li>
<li class="chapter" data-level="4.13.6" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#koper-fil"><i class="fa fa-check"></i><b>4.13.6</b> Koper na filtratie</a></li>
<li class="chapter" data-level="4.13.7" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#uranium"><i class="fa fa-check"></i><b>4.13.7</b> Uranium</a></li>
<li class="chapter" data-level="4.13.8" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#uranium-fil"><i class="fa fa-check"></i><b>4.13.8</b> Uranium na filtratie</a></li>
<li class="chapter" data-level="4.13.9" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#vanadium"><i class="fa fa-check"></i><b>4.13.9</b> Vanadium</a></li>
<li class="chapter" data-level="4.13.10" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#vanadium-fil"><i class="fa fa-check"></i><b>4.13.10</b> Vanadium na filtratie</a></li>
<li class="chapter" data-level="4.13.11" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#zink"><i class="fa fa-check"></i><b>4.13.11</b> Zink</a></li>
<li class="chapter" data-level="4.13.12" data-path="fysisch-oppwater.html"><a href="fysisch-oppwater.html#zink-fil"><i class="fa fa-check"></i><b>4.13.12</b> Zink na filtratie</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="zwevend-stof.html"><a href="zwevend-stof.html"><i class="fa fa-check"></i><b>5</b> Zwevend stof - Fysisch-chemische parameters</a>
<ul>
<li class="chapter" data-level="5.1" data-path="zwevend-stof.html"><a href="zwevend-stof.html#zwevend-info-metingen"><i class="fa fa-check"></i><b>5.1</b> Informatie over de metingen</a></li>
<li class="chapter" data-level="5.2" data-path="zwevend-stof.html"><a href="zwevend-stof.html#korrelgrootteverdeling"><i class="fa fa-check"></i><b>5.2</b> Korrelgrootteverdeling</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="zwevend-stof.html"><a href="zwevend-stof.html#korrelgrootteverdeling-tot63"><i class="fa fa-check"></i><b>5.2.1</b> Korrelgroottefractie tot 63 <span class="math inline">\(\mu\)</span>m</a></li>
<li class="chapter" data-level="5.2.2" data-path="zwevend-stof.html"><a href="zwevend-stof.html#korrelgrootteverdeling-tot2"><i class="fa fa-check"></i><b>5.2.2</b> Korrelgroottefractie tot 2 <span class="math inline">\(\mu\)</span>m</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="zwevend-stof.html"><a href="zwevend-stof.html#zwevend-metalen"><i class="fa fa-check"></i><b>5.3</b> Metalen</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="zwevend-stof.html"><a href="zwevend-stof.html#zwevend-arseen"><i class="fa fa-check"></i><b>5.3.1</b> Arseen</a></li>
<li class="chapter" data-level="5.3.2" data-path="zwevend-stof.html"><a href="zwevend-stof.html#zwevend-cadmium"><i class="fa fa-check"></i><b>5.3.2</b> Cadmium</a></li>
<li class="chapter" data-level="5.3.3" data-path="zwevend-stof.html"><a href="zwevend-stof.html#zwevend-chroom"><i class="fa fa-check"></i><b>5.3.3</b> Chroom</a></li>
<li class="chapter" data-level="5.3.4" data-path="zwevend-stof.html"><a href="zwevend-stof.html#zwevend-kobalt"><i class="fa fa-check"></i><b>5.3.4</b> Kobalt</a></li>
<li class="chapter" data-level="5.3.5" data-path="zwevend-stof.html"><a href="zwevend-stof.html#zwevend-koper"><i class="fa fa-check"></i><b>5.3.5</b> Koper</a></li>
<li class="chapter" data-level="5.3.6" data-path="zwevend-stof.html"><a href="zwevend-stof.html#zwevend-kwik"><i class="fa fa-check"></i><b>5.3.6</b> Kwik</a></li>
<li class="chapter" data-level="5.3.7" data-path="zwevend-stof.html"><a href="zwevend-stof.html#zwevend-lood"><i class="fa fa-check"></i><b>5.3.7</b> Lood</a></li>
<li class="chapter" data-level="5.3.8" data-path="zwevend-stof.html"><a href="zwevend-stof.html#zwevend-vanadium"><i class="fa fa-check"></i><b>5.3.8</b> Vanadium</a></li>
<li class="chapter" data-level="5.3.9" data-path="zwevend-stof.html"><a href="zwevend-stof.html#zwevend-zink"><i class="fa fa-check"></i><b>5.3.9</b> Zink</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="zwevend-stof.html"><a href="zwevend-stof.html#zwevend-PAK"><i class="fa fa-check"></i><b>5.4</b> Polycyclische aromatische koolwaterstoffen (PAK’s)</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="zwevend-stof.html"><a href="zwevend-stof.html#zwevend-antraceen"><i class="fa fa-check"></i><b>5.4.1</b> Antraceen</a></li>
<li class="chapter" data-level="5.4.2" data-path="zwevend-stof.html"><a href="zwevend-stof.html#zwevend-Benzoapyreen"><i class="fa fa-check"></i><b>5.4.2</b> Benzo[<em>a</em>]pyreen</a></li>
<li class="chapter" data-level="5.4.3" data-path="zwevend-stof.html"><a href="zwevend-stof.html#zwevend-Benzoghiperyleen"><i class="fa fa-check"></i><b>5.4.3</b> Benzo[<em>g,h,i</em>]peryleen</a></li>
<li class="chapter" data-level="5.4.4" data-path="zwevend-stof.html"><a href="zwevend-stof.html#zwevend-Benzoaantraceen"><i class="fa fa-check"></i><b>5.4.4</b> Benzo[<em>a</em>]antraceen</a></li>
<li class="chapter" data-level="5.4.5" data-path="zwevend-stof.html"><a href="zwevend-stof.html#zwevend-Benzokfluorantheen"><i class="fa fa-check"></i><b>5.4.5</b> Benzo[<em>k</em>]fluorantheen</a></li>
<li class="chapter" data-level="5.4.6" data-path="zwevend-stof.html"><a href="zwevend-stof.html#zwevend-chryseen"><i class="fa fa-check"></i><b>5.4.6</b> Chryseen</a></li>
<li class="chapter" data-level="5.4.7" data-path="zwevend-stof.html"><a href="zwevend-stof.html#zwevend-fenanthreen"><i class="fa fa-check"></i><b>5.4.7</b> Fenanthreen</a></li>
<li class="chapter" data-level="5.4.8" data-path="zwevend-stof.html"><a href="zwevend-stof.html#zwevend-fluorantheen"><i class="fa fa-check"></i><b>5.4.8</b> Fluorantheen</a></li>
<li class="chapter" data-level="5.4.9" data-path="zwevend-stof.html"><a href="zwevend-stof.html#zwevend-indeno"><i class="fa fa-check"></i><b>5.4.9</b> Indeno[<em>1,2,3-c,d</em>]pyreen</a></li>
<li class="chapter" data-level="5.4.10" data-path="zwevend-stof.html"><a href="zwevend-stof.html#zwevend-naftaleen"><i class="fa fa-check"></i><b>5.4.10</b> Naftaleen</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="zwevend-stof.html"><a href="zwevend-stof.html#zwevend-PCB"><i class="fa fa-check"></i><b>5.5</b> Polychloorbifenylen (PCB’s)</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="zwevend-stof.html"><a href="zwevend-stof.html#zwevend-PCB180"><i class="fa fa-check"></i><b>5.5.1</b> PCB180</a></li>
<li class="chapter" data-level="5.5.2" data-path="zwevend-stof.html"><a href="zwevend-stof.html#zwevend-PCB138"><i class="fa fa-check"></i><b>5.5.2</b> PCB138</a></li>
<li class="chapter" data-level="5.5.3" data-path="zwevend-stof.html"><a href="zwevend-stof.html#zwevend-PCB153"><i class="fa fa-check"></i><b>5.5.3</b> PCB153</a></li>
<li class="chapter" data-level="5.5.4" data-path="zwevend-stof.html"><a href="zwevend-stof.html#zwevend-PCB101"><i class="fa fa-check"></i><b>5.5.4</b> PCB101</a></li>
<li class="chapter" data-level="5.5.5" data-path="zwevend-stof.html"><a href="zwevend-stof.html#zwevend-PCB52"><i class="fa fa-check"></i><b>5.5.5</b> PCB52</a></li>
<li class="chapter" data-level="5.5.6" data-path="zwevend-stof.html"><a href="zwevend-stof.html#zwevend-PCB118"><i class="fa fa-check"></i><b>5.5.6</b> PCB118</a></li>
<li class="chapter" data-level="5.5.7" data-path="zwevend-stof.html"><a href="zwevend-stof.html#zwevend-PCB28"><i class="fa fa-check"></i><b>5.5.7</b> PCB28</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="zwevend-stof.html"><a href="zwevend-stof.html#zwevend-overig"><i class="fa fa-check"></i><b>5.6</b> Overige stoffen</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="zwevend-stof.html"><a href="zwevend-stof.html#zwevend-dieldrin"><i class="fa fa-check"></i><b>5.6.1</b> Dieldrin</a></li>
<li class="chapter" data-level="5.6.2" data-path="zwevend-stof.html"><a href="zwevend-stof.html#zwevend-Hexachloorbenzeen"><i class="fa fa-check"></i><b>5.6.2</b> Hexachloorbenzeen</a></li>
<li class="chapter" data-level="5.6.3" data-path="zwevend-stof.html"><a href="zwevend-stof.html#zwevend-Tributyltin"><i class="fa fa-check"></i><b>5.6.3</b> Tributyltin</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="bodem.html"><a href="bodem.html"><i class="fa fa-check"></i><b>6</b> Bodem - Fysisch-chemische parameters</a>
<ul>
<li class="chapter" data-level="6.1" data-path="bodem.html"><a href="bodem.html#bodem-info-metingen"><i class="fa fa-check"></i><b>6.1</b> Informatie over de metingen</a></li>
<li class="chapter" data-level="6.2" data-path="bodem.html"><a href="bodem.html#bodem-metalen"><i class="fa fa-check"></i><b>6.2</b> Metalen</a></li>
<li class="chapter" data-level="6.3" data-path="bodem.html"><a href="bodem.html#bodem-PAK"><i class="fa fa-check"></i><b>6.3</b> Polycyclische Aromatische Koolwaterstoffen (PAK’s)</a></li>
<li class="chapter" data-level="6.4" data-path="bodem.html"><a href="bodem.html#bodem-PCB"><i class="fa fa-check"></i><b>6.4</b> Polychloorbifenylen (PCB’s)</a></li>
<li class="chapter" data-level="6.5" data-path="bodem.html"><a href="bodem.html#bodem-organotin"><i class="fa fa-check"></i><b>6.5</b> Organotinverbindingen</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="fytoplankton.html"><a href="fytoplankton.html"><i class="fa fa-check"></i><b>7</b> Fytoplankton</a>
<ul>
<li class="chapter" data-level="7.1" data-path="fytoplankton.html"><a href="fytoplankton.html#fyto-soorten"><i class="fa fa-check"></i><b>7.1</b> Indeling soorten</a></li>
<li class="chapter" data-level="7.2" data-path="fytoplankton.html"><a href="fytoplankton.html#fyto-info-metingen"><i class="fa fa-check"></i><b>7.2</b> Informatie over de metingen</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="fytoplankton.html"><a href="fytoplankton.html#fyto-metingen-stations"><i class="fa fa-check"></i><b>7.2.1</b> Stations en jaren</a></li>
<li class="chapter" data-level="7.2.2" data-path="fytoplankton.html"><a href="fytoplankton.html#fyto-metingen-figuren"><i class="fa fa-check"></i><b>7.2.2</b> Figuren</a></li>
<li class="chapter" data-level="7.2.3" data-path="fytoplankton.html"><a href="fytoplankton.html#fyto-metingen-trendbreuk"><i class="fa fa-check"></i><b>7.2.3</b> Trendbreuk</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="fytoplankton.html"><a href="fytoplankton.html#fyto-resultaten-station"><i class="fa fa-check"></i><b>7.3</b> Resultaten per station</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="fytoplankton.html"><a href="fytoplankton.html#fyto-resultaten-schaar"><i class="fa fa-check"></i><b>7.3.1</b> Schaar van Ouden Doel</a></li>
<li class="chapter" data-level="7.3.2" data-path="fytoplankton.html"><a href="fytoplankton.html#fyto-resultaten-hansweert"><i class="fa fa-check"></i><b>7.3.2</b> Hansweert geul</a></li>
<li class="chapter" data-level="7.3.3" data-path="fytoplankton.html"><a href="fytoplankton.html#fyto-resultaten-vlis"><i class="fa fa-check"></i><b>7.3.3</b> Vlissingen boei SSVH</a></li>
<li class="chapter" data-level="7.3.4" data-path="fytoplankton.html"><a href="fytoplankton.html#fyto-resultaten-walch2km"><i class="fa fa-check"></i><b>7.3.4</b> Walcheren 2 km uit de kust</a></li>
<li class="chapter" data-level="7.3.5" data-path="fytoplankton.html"><a href="fytoplankton.html#fyto-resultaten-walch20km"><i class="fa fa-check"></i><b>7.3.5</b> Walcheren 20 km uit de kust</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="fytoplankton.html"><a href="fytoplankton.html#fyto-resultaten-groep"><i class="fa fa-check"></i><b>7.4</b> Resultaten per groep</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="fytoplankton.html"><a href="fytoplankton.html#fyto-resultaten-auto-blauw"><i class="fa fa-check"></i><b>7.4.1</b> Autotroof - Blauwwieren</a></li>
<li class="chapter" data-level="7.4.2" data-path="fytoplankton.html"><a href="fytoplankton.html#fyto-resultaten-auto-dia"><i class="fa fa-check"></i><b>7.4.2</b> Autotroof - Diatomeeën</a></li>
<li class="chapter" data-level="7.4.3" data-path="fytoplankton.html"><a href="fytoplankton.html#fyto-resultaten-auto-dino"><i class="fa fa-check"></i><b>7.4.3</b> Autotroof - Dinoflagellaten</a></li>
<li class="chapter" data-level="7.4.4" data-path="fytoplankton.html"><a href="fytoplankton.html#fyto-resultaten-auto-groen"><i class="fa fa-check"></i><b>7.4.4</b> Autotroof - Groenwieren</a></li>
<li class="chapter" data-level="7.4.5" data-path="fytoplankton.html"><a href="fytoplankton.html#fyto-resultaten-auto-phaeo"><i class="fa fa-check"></i><b>7.4.5</b> Autotroof - Phaeocystis</a></li>
<li class="chapter" data-level="7.4.6" data-path="fytoplankton.html"><a href="fytoplankton.html#fyto-resultaten-auto-overig"><i class="fa fa-check"></i><b>7.4.6</b> Autotroof - overig</a></li>
<li class="chapter" data-level="7.4.7" data-path="fytoplankton.html"><a href="fytoplankton.html#fyto-resultaten-hetero-dino"><i class="fa fa-check"></i><b>7.4.7</b> Heterotroof - Dinoflagellaten</a></li>
<li class="chapter" data-level="7.4.8" data-path="fytoplankton.html"><a href="fytoplankton.html#fyto-resultaten-hetero-overig"><i class="fa fa-check"></i><b>7.4.8</b> Heterotroof - overig</a></li>
<li class="chapter" data-level="7.4.9" data-path="fytoplankton.html"><a href="fytoplankton.html#fyto-resultaten-mix-dino"><i class="fa fa-check"></i><b>7.4.9</b> Mixotroof - dinoflagellaten</a></li>
<li class="chapter" data-level="7.4.10" data-path="fytoplankton.html"><a href="fytoplankton.html#fyto-resultaten-mix-overig"><i class="fa fa-check"></i><b>7.4.10</b> Mixotroof - overig</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Concept Eerstelijnsrapportage Westerschelde (IN ONTWIKKELING)</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="shortcut icon" type="image/jpg" href="navbar/images/icon-deltares.svg"/>
</head>
<body>

<nav class="navigation-bar">
    <a href="index.html"><i class="fa fa-home"></i></a>
    <div class="logos">
        <img class="logo" src="navbar/images/deltares_logo.png" />
        <img class="logo" src="navbar/images/Rijkswaterstaat-logo-e1473888123824-1-300x300.jpg" />
    </div>
</nav>

</body>
</html>
<div id="zwevend-stof" class="section level1" number="5">
<h1><span class="header-section-number">5</span> Zwevend stof - Fysisch-chemische parameters</h1>
<p>Voor de bepaling van de fysisch-chemische parameters in het oppervlaktewater en in zwevend stof vinden in het kader van MWTL vaartochten plaats, waarbij op vaste punten monsters worden genomen op ca. 1,5 m onder het wateroppervlak. In dit hoofdstuk zijn de metingen in zwevend stof opgenomen. In het algemeen geldt dat sinds 1998 de waardes van de verontreinigingen zijn afgenomen. Er zijn indicaties dat deze afnemende trend minder lijkt te worden en dat de concentraties lijken zich te stabiliseren en de data van 2018 passen in dit beeld.</p>
<div id="zwevend-info-metingen" class="section level2" number="5.1">
<h2><span class="header-section-number">5.1</span> Informatie over de metingen</h2>
<p>Voor de bepaling van de fysisch-chemische parameters in het zwevend stof vinden in het kader van MWTL maandelijkse vaartochten (tochtnummer 11) plaats, die de locaties Schaar van Ouden Doel en Vlissingen boei SSVH bemonsteren. Bij Schaar van Ouden Doel wordt maandelijks gemeten en bij Vlissingen eens per kwartaal. De monsters worden genomen met een doorstroomcentrifuge, waarbij een bepaalde hoeveelheid slib moet worden verzameld en afgeleverd aan het laboratorium voor analyse. In verband met het getij wordt ook altijd de saliniteit gemeten, zie Paragraaf <a href="fysisch-oppwater.html#saliniteit">4.2</a>. De stations zijn gepresenteerd in Figuur <a href="zwevend-stof.html#fig:meetstationsZwevend">5.1</a> en zijn steeds gerangschikt in stroomafwaartse richting.</p>
<div class="figure" style="text-align: center"><span id="fig:meetstationsZwevend"></span>
<div id="htmlwidget-48bb740e25251c3805b1" style="width:85%;height:576px;" class="leaflet html-widget"></div>
<script type="application/json" data-for="htmlwidget-48bb740e25251c3805b1">{"x":{"options":{"crs":{"crsClass":"L.CRS.EPSG3857","code":null,"proj4def":null,"projectedBounds":null,"options":{}}},"calls":[{"method":"addTiles","args":["//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",null,null,{"minZoom":0,"maxZoom":18,"tileSize":256,"subdomains":"abc","errorTileUrl":"","tms":false,"noWrap":false,"zoomOffset":0,"zoomReverse":false,"opacity":1,"zIndex":1,"detectRetina":false,"attribution":"&copy; <a href=\"http://openstreetmap.org\">OpenStreetMap<\/a> contributors, <a href=\"http://creativecommons.org/licenses/by-sa/2.0/\">CC-BY-SA<\/a>"}]},{"method":"addCircleMarkers","args":[[51.3504699785602,51.41288731],[4.25069371004744,3.56579345],10,null,null,{"interactive":true,"className":"","stroke":true,"color":"#03F","weight":5,"opacity":0.5,"fill":true,"fillColor":"#03F","fillOpacity":0.2},null,null,null,null,["Schaar van Ouden Doel","Vlissingen boei SSVH"],{"interactive":false,"permanent":true,"direction":"auto","opacity":1,"offset":[0,0],"textsize":"10px","textOnly":false,"className":"","sticky":true},null]}],"limits":{"lat":[51.3504699785602,51.41288731],"lng":[3.56579345,4.25069371004744]}},"evals":[],"jsHooks":[]}</script>
<p class="caption">
Figuur 5.1: Ligging van de meetstations voor het zwevende stof
</p>
</div>
<p>De meetdata worden gepresenteerd door middel van jaargemiddelden, en de minimale en maximale waarde die in elk jaar gemeten is. Voor sommige parameters zijn ook maandgemiddelden en/of seizoensgemiddelden weergegeven. Als er slechts een meting per maand beschikbaar is (of minder), zijn deze waardes gepresenteerd. Bij het middelen van parameters over een bepaalde periode is de datadichtheid van belang. Een overzicht van het aantal metingen per parameter, per station, per jaar is daarom opgenomen in Bijlage <a href="#BijlageB-meetdichtheid-zwevend"><strong>??</strong></a>.</p>
<p>Voor sommige parameters geldt dat de meetwaarde gelijk of lager is dan de detectiegrens van het meetinstrument. Indien dit het geval is, wordt dit beschreven in de begeleidende tekst en de detectiegrens meegenomen als meetwaarde. Hierdoor kunnen gemiddelden een iets hogere waarde weergeven dan wanneer gemiddeld was over de waarden die daadwerkelijk hebben plaatsgevonden. Daarnaast is meestal een lineaire trendlijn vanaf het jaar 2000 toegevoegd, zodat de trend niet direct beïnvloed wordt door de tweede verruiming in 1997-1998. Gemiddelde, minimale en maximale waardes in bijgevoegde tabellen zijn gebaseerd over de tijdsperiode weergegeven in de bijbehorende figuren.</p>
</div>
<div id="korrelgrootteverdeling" class="section level2" number="5.2">
<h2><span class="header-section-number">5.2</span> Korrelgrootteverdeling</h2>
<p>In de resultaten hebben we het minerale aandeel van de korrelgrootteverdeling weergegeven, dat wil zeggen dat kalk en organische stof verwijderd zijn, als percentage van het totale gewicht van het monster. De korrelgroottefractie kleiner dan 2 <span class="math inline">\(\mu\)</span>m wordt bij Schaar van Ouden Doel enkel vanaf 1998 weergegeven. Na 1997 heeft er een methodiekverandering plaatsgevonden waardoor de gegevens van voor 1998 niet vergelijkbaar zijn met die van na 1998.</p>
<div id="korrelgrootteverdeling-tot63" class="section level3" number="5.2.1">
<h3><span class="header-section-number">5.2.1</span> Korrelgroottefractie tot 63 <span class="math inline">\(\mu\)</span>m</h3>
<p>Figuur <a href="#fig:zwevendKorrelgroottefractietot63um"><strong>??</strong></a> toont het jaargemiddelde korrelgroottefractie tot 63 <span class="math inline">\(\mu\)</span>m per station voor de periode vanaf 1997 t/m 2019, samen met de laagste en de hoogste gemeten waarde per jaar. Daarnaast zijn in Tabel <a href="zwevend-stof.html#tab:zwevendKorrelgroottefractietot63umTab">5.1</a> de gemiddelde, minimale en maximale waardes per station weergegeven.</p>
<p>De korrelgroottefractie kleiner dan 63 <span class="math inline">\(\mu\)</span>m ligt rond 60% bij Vlissingen boei SSVH en rond de 70% bij Schaar van Ouden Doel. Er zijn geen significante temporele trends bij beide stations.</p>
<table>
<caption><span id="tab:zwevendKorrelgroottefractietot63umTab">Tabel 5.1: </span>Jaarlijks mediaan, 10-percentiel en 90-percentiel en de trend en p waarde van de trend van korrelgrootte tot 63 <span class="math inline">\(\mu\)</span>m (%) van het zwevende stof van de Westerschelde en de monding berekend op alle beschikbare data vanaf 1996.</caption>
<thead>
<tr class="header">
<th align="center">Station</th>
<th align="center">Mediaan</th>
<th align="center">90-perc</th>
<th align="center">10-perc</th>
<th align="center">Trend</th>
<th align="center">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Schaar van Ouden Doel</td>
<td align="center">69.0</td>
<td align="center">73.0</td>
<td align="center">63.1</td>
<td align="center">0.257</td>
<td align="center">0.001</td>
</tr>
<tr class="even">
<td align="center">Vlissingen boei SSVH</td>
<td align="center">59.9</td>
<td align="center">70.2</td>
<td align="center">53.4</td>
<td align="center">0.554</td>
<td align="center">0.004</td>
</tr>
</tbody>
</table>
<div class="figure" style="text-align: center"><span id="fig:zwevendKorrelgroottefractietot63um-1"></span>
<img src="_main_files/figure-html/zwevendKorrelgroottefractietot63um-1.png" alt="Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van de korrelgroottefractie tot 63$\mu$m voor 2 stations." width="85%" />
<p class="caption">
Figuur 5.2: Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van de korrelgroottefractie tot 63<span class="math inline">\(\mu\)</span>m voor 2 stations.
</p>
</div>
<div class="figure" style="text-align: center"><span id="fig:zwevendKorrelgroottefractietot63um-2"></span>
<img src="_main_files/figure-html/zwevendKorrelgroottefractietot63um-2.png" alt="Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van de korrelgroottefractie tot 63$\mu$m voor 2 stations." width="85%" />
<p class="caption">
Figuur 5.3: Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van de korrelgroottefractie tot 63<span class="math inline">\(\mu\)</span>m voor 2 stations.
</p>
</div>
</div>
<div id="korrelgrootteverdeling-tot2" class="section level3" number="5.2.2">
<h3><span class="header-section-number">5.2.2</span> Korrelgroottefractie tot 2 <span class="math inline">\(\mu\)</span>m</h3>
<p>Figuur <a href="zwevend-stof.html#fig:zwevendKorrelgroottefractietot2um">5.4</a> toont het jaargemiddelde korrelgroottefractie tot 2 <span class="math inline">\(\mu\)</span>m per station voor de periode vanaf 1997 t/m 2019, samen met de laagste en de hoogste gemeten waarde per jaar. Daarnaast zijn in Tabel <a href="zwevend-stof.html#tab:zwevendKorrelgroottefractietot2umTab">5.2</a> zijn de gemiddelde, minimale en maximale waardes per station weergegeven.</p>
<p>De korrelgroottefractie kleiner dan 2 <span class="math inline">\(\mu\)</span>m ligt rond 35% bij Schaar van Ouden Doel net als bij Vlissingen.</p>
<table>
<caption><span id="tab:zwevendKorrelgroottefractietot2umTab">Tabel 5.2: </span>Jaarlijks mediaan, 10-percentiel en 90-percentiel en de trend en p waarde van de trend van korrelgrootte tot 2 <span class="math inline">\(\mu\)</span>m (%) van het zwevende stof van de Westerschelde en de monding berekend op alle beschikbare data vanaf 1996.</caption>
<thead>
<tr class="header">
<th align="center">Station</th>
<th align="center">Mediaan</th>
<th align="center">90-perc</th>
<th align="center">10-perc</th>
<th align="center">Trend</th>
<th align="center">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Schaar van Ouden Doel</td>
<td align="center">39.1</td>
<td align="center">45.2</td>
<td align="center">33.0</td>
<td align="center">0.080</td>
<td align="center">0.576</td>
</tr>
<tr class="even">
<td align="center">Vlissingen boei SSVH</td>
<td align="center">29.6</td>
<td align="center">35.0</td>
<td align="center">23.9</td>
<td align="center">0.316</td>
<td align="center">0.006</td>
</tr>
</tbody>
</table>
<div class="figure" style="text-align: center"><span id="fig:zwevendKorrelgroottefractietot2um"></span>
<img src="_main_files/figure-html/zwevendKorrelgroottefractietot2um-1.png" alt="Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van de korrelgroottefractie tot 2$\mu$m voor beide stations" width="85%" />
<p class="caption">
Figuur 5.4: Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van de korrelgroottefractie tot 2<span class="math inline">\(\mu\)</span>m voor beide stations
</p>
</div>
</div>
</div>
<div id="zwevend-metalen" class="section level2" number="5.3">
<h2><span class="header-section-number">5.3</span> Metalen</h2>
<p>In deze paragraaf presenteren we de volgende metalen gedetecteerd in zwevende stof.</p>
<ul>
<li>Arseen (As, Figuur <a href="#fig:zwevendArseen"><strong>??</strong></a>)</li>
<li>Cadmium (Cd Figuur <a href="#fig:zwevendCadmium"><strong>??</strong></a>)</li>
<li>Chroom (Cr, Figuur <a href="#fig:zwevendChroom"><strong>??</strong></a>)</li>
<li>Kobalt (Co, Figuur <a href="zwevend-stof.html#fig:zwevendKobalt">5.11</a>)</li>
<li>Koper (Cu, Figuur <a href="zwevend-stof.html#fig:zwevendKoper">5.12</a>)</li>
<li>Kwik (Hg, Figuur <a href="zwevend-stof.html#fig:zwevendKwik">5.13</a>)</li>
<li>Lood (Pb, Figuur <a href="zwevend-stof.html#fig:zwevendLood">5.14</a>)</li>
<li>Vanadium (V, Figuur <a href="zwevend-stof.html#fig:zwevendVanadium">5.15</a>)</li>
<li>Zink (Zn, Figuur <a href="zwevend-stof.html#fig:zwevendZink">5.16</a>)</li>
</ul>
<div id="zwevend-arseen" class="section level3" number="5.3.1">
<h3><span class="header-section-number">5.3.1</span> Arseen</h3>
<p>Figuur <a href="#fig:zwevendArseen"><strong>??</strong></a> toont het jaargemiddelde arseen per station voor de periode vanaf 1996 t/m 2019, samen met de laagste en de hoogste gemeten waarde per jaar. Daarnaast zijn in Tabel <a href="zwevend-stof.html#tab:zwevendArseenTab">5.3</a> de gemiddelde, minimale en maximale waardes per station weergegeven.</p>
<p>De concentraties arseen in zwevende stof nemen iets af in stroomafwaartse richting. Bij Schaar van Ouden Doel zijn slechts enkele meetwaarden beschikbaar. Sinds 2011 nemen de waarden af. Over de gehele meetperiode is de trend niet significant. Bij Vlissingen boei SSVH is er een licht dalende trend (-0,18 mg/kg per jaar) in de periode 2000-2012 die statistisch significant is.</p>
<table>
<caption><span id="tab:zwevendArseenTab">Tabel 5.3: </span>Jaarlijks mediaan, 10-percentiel en 90-percentiel en de trend en p waarde van de trend van arseen (mg/kg) van het zwevende stof van de Westerschelde en de monding berekend op alle beschikbare data vanaf 1996.</caption>
<thead>
<tr class="header">
<th align="center">Station</th>
<th align="center">Mediaan</th>
<th align="center">90-perc</th>
<th align="center">10-perc</th>
<th align="center">Trend</th>
<th align="center">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Schaar van Ouden Doel</td>
<td align="center">28.1</td>
<td align="center">31.2</td>
<td align="center">24.6</td>
<td align="center">-0.020</td>
<td align="center">0.856</td>
</tr>
<tr class="even">
<td align="center">Vlissingen boei SSVH</td>
<td align="center">17.0</td>
<td align="center">19.8</td>
<td align="center">14.3</td>
<td align="center">-0.147</td>
<td align="center">0.000</td>
</tr>
</tbody>
</table>
<div class="figure" style="text-align: center"><span id="fig:zwevendArseen-1"></span>
<img src="_main_files/figure-html/zwevendArseen-1.png" alt="Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Arseen voor beide stations." width="85%" />
<p class="caption">
Figuur 5.5: Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Arseen voor beide stations.
</p>
</div>
<div class="figure" style="text-align: center"><span id="fig:zwevendArseen-2"></span>
<img src="_main_files/figure-html/zwevendArseen-2.png" alt="Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Arseen voor beide stations." width="85%" />
<p class="caption">
Figuur 5.6: Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Arseen voor beide stations.
</p>
</div>
</div>
<div id="zwevend-cadmium" class="section level3" number="5.3.2">
<h3><span class="header-section-number">5.3.2</span> Cadmium</h3>
<p>Figuur <a href="#fig:zwevendCadmium"><strong>??</strong></a> toont het jaargemiddelde Cadmium per station voor de periode vanaf 1997 t/m 2019, samen met de laagste en de hoogste gemeten waarde per jaar. Daarnaast zijn in Tabel <a href="zwevend-stof.html#tab:zwevendCadmiumTab">5.4</a> zijn de gemiddelde, minimale en maximale waardes per station weergegeven.</p>
<p>De concentraties cadmium in zwevende stof nemen sterk af in stroomafwaartse richting (factor 5 tussen de twee stations). Bij Schaar van Ouden Doel is er een dalende trend van 0,13 mg/kg per jaar aanwezig die statistisch significant is. De waardes bij Vlissingen zijn constant over tijd.</p>
<table>
<caption><span id="tab:zwevendCadmiumTab">Tabel 5.4: </span>Jaarlijks mediaan, 10-percentiel en 90-percentiel en de trend en p waarde van de trend van cadmium (mg/kg) van het zwevende stof van de Westerschelde en de monding berekend op alle beschikbare data vanaf 1996.</caption>
<thead>
<tr class="header">
<th align="center">Station</th>
<th align="center">Mediaan</th>
<th align="center">90-perc</th>
<th align="center">10-perc</th>
<th align="center">Trend</th>
<th align="center">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Schaar van Ouden Doel</td>
<td align="center">3.70</td>
<td align="center">5.350</td>
<td align="center">2.38</td>
<td align="center">-0.131</td>
<td align="center">0</td>
</tr>
<tr class="even">
<td align="center">Vlissingen boei SSVH</td>
<td align="center">0.51</td>
<td align="center">0.676</td>
<td align="center">0.40</td>
<td align="center">-0.008</td>
<td align="center">0</td>
</tr>
</tbody>
</table>
<div class="figure" style="text-align: center"><span id="fig:zwevendCadmium-1"></span>
<img src="_main_files/figure-html/zwevendCadmium-1.png" alt="Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Cadmium voor beide stations." width="85%" />
<p class="caption">
Figuur 5.7: Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Cadmium voor beide stations.
</p>
</div>
<div class="figure" style="text-align: center"><span id="fig:zwevendCadmium-2"></span>
<img src="_main_files/figure-html/zwevendCadmium-2.png" alt="Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Cadmium voor beide stations." width="85%" />
<p class="caption">
Figuur 5.8: Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Cadmium voor beide stations.
</p>
</div>
</div>
<div id="zwevend-chroom" class="section level3" number="5.3.3">
<h3><span class="header-section-number">5.3.3</span> Chroom</h3>
<p>Figuur <a href="#fig:zwevendChroom"><strong>??</strong></a> toont het jaargemiddelde chroom per station voor de periode vanaf 1996 t/m 2019, samen met de laagste en de hoogste gemeten waarde per jaar. Daarnaast zijn in Tabel <a href="zwevend-stof.html#tab:zwevendChroomTab">5.5</a> de gemiddelde, minimale en maximale waardes per station weergegeven.</p>
<p>De concentraties chroom in zwevende stof nemen af in stroomafwaartse richting. Bij Schaar van Ouden Doel zit sinds 2005 weinig verandering in de gemeten chroomgehaltes. De situatie bij Vlissingen boei SSVH toont voor de periode 1996-2011 een stabiele situatie, maar sinds 2012 liggen de waarden een stuk lager. Over de gehele dataset neemt het hoeveelheid chroom in zwevende stof af met 1,8 mg/kg per jaar. Een trend die statistisch significant is.</p>
<table>
<caption><span id="tab:zwevendChroomTab">Tabel 5.5: </span>Jaarlijks mediaan, 10-percentiel en 90-percentiel en de trend en p waarde van de trend van chroom (mg/kg) van het zwevende stof van de Westerschelde en de monding berekend op alle beschikbare data vanaf 1996.</caption>
<thead>
<tr class="header">
<th align="center">Station</th>
<th align="center">Mediaan</th>
<th align="center">90-perc</th>
<th align="center">10-perc</th>
<th align="center">Trend</th>
<th align="center">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Schaar van Ouden Doel</td>
<td align="center">103</td>
<td align="center">131.0</td>
<td align="center">88.1</td>
<td align="center">-1.60</td>
<td align="center">0</td>
</tr>
<tr class="even">
<td align="center">Vlissingen boei SSVH</td>
<td align="center">74</td>
<td align="center">85.4</td>
<td align="center">50.4</td>
<td align="center">-1.44</td>
<td align="center">0</td>
</tr>
</tbody>
</table>
<div class="figure" style="text-align: center"><span id="fig:zwevendChroom-1"></span>
<img src="_main_files/figure-html/zwevendChroom-1.png" alt="Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Chroom voor beide stations." width="85%" />
<p class="caption">
Figuur 5.9: Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Chroom voor beide stations.
</p>
</div>
<div class="figure" style="text-align: center"><span id="fig:zwevendChroom-2"></span>
<img src="_main_files/figure-html/zwevendChroom-2.png" alt="Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Chroom voor beide stations." width="85%" />
<p class="caption">
Figuur 5.10: Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Chroom voor beide stations.
</p>
</div>
</div>
<div id="zwevend-kobalt" class="section level3" number="5.3.4">
<h3><span class="header-section-number">5.3.4</span> Kobalt</h3>
<p>Figuur <a href="zwevend-stof.html#fig:zwevendKobalt">5.11</a> toont het jaargemiddelde kobalt per station voor de periode vanaf 1996 t/m 2019, samen met de laagste en de hoogste gemeten waarde per jaar. Daarnaast zijn in Tabel <a href="zwevend-stof.html#tab:zwevendKobaltTab">5.6</a> de gemiddelde, minimale en maximale waardes per station weergegeven.</p>
<p>De concentraties kobalt in zwevende stof nemen af in stroomafwaartse richting. Bij Vlissingen is de correlatie in de data het duidelijkst. De kobaltconcentraties nemen af in de tijd, echter wel met lage significantie. Bij Schaar van Ouden Doel is er geen significante trend waarneembaar.</p>
<table>
<caption><span id="tab:zwevendKobaltTab">Tabel 5.6: </span>Jaarlijks mediaan, 10-percentiel en 90-percentiel en de trend en p waarde van de trend van kobalt (mg/kg) van het zwevende stof van de Westerschelde en de monding berekend op alle beschikbare data vanaf 1996.</caption>
<thead>
<tr class="header">
<th align="center">Station</th>
<th align="center">Mediaan</th>
<th align="center">90-perc</th>
<th align="center">10-perc</th>
<th align="center">Trend</th>
<th align="center">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Schaar van Ouden Doel</td>
<td align="center">16.00</td>
<td align="center">17.4</td>
<td align="center">14.10</td>
<td align="center">-0.001</td>
<td align="center">0.979</td>
</tr>
<tr class="even">
<td align="center">Vlissingen boei SSVH</td>
<td align="center">8.19</td>
<td align="center">9.8</td>
<td align="center">7.06</td>
<td align="center">-0.071</td>
<td align="center">0.009</td>
</tr>
</tbody>
</table>
<div class="figure" style="text-align: center"><span id="fig:zwevendKobalt"></span>
<img src="_main_files/figure-html/zwevendKobalt-1.png" alt="Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Kobalt voor beide stations." width="85%" />
<p class="caption">
Figuur 5.11: Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Kobalt voor beide stations.
</p>
</div>
</div>
<div id="zwevend-koper" class="section level3" number="5.3.5">
<h3><span class="header-section-number">5.3.5</span> Koper</h3>
<p>Figuur <a href="zwevend-stof.html#fig:zwevendKoper">5.12</a> toont het jaargemiddelde koper per station voor de periode vanaf 1996 t/m 2019, samen met de laagste en de hoogste gemeten waarde per jaar. Daarnaast zijn in Tabel <a href="zwevend-stof.html#tab:zwevendKoperTab">5.7</a> de gemiddelde, minimale en maximale waardes per station weergegeven.</p>
<p>De concentraties koper in zwevende stof nemen sterk af in stroomafwaartse richting (factor 2,7) . Er zijn sterke uitschieters in koperconcentraties op beide stations.De reden hiervoor is onbekend. Dit heeft wel invloed op de analyse van de trend die door de uitschieters niet meer significant is.</p>
<table>
<caption><span id="tab:zwevendKoperTab">Tabel 5.7: </span>Jaarlijks mediaan, 10-percentiel en 90-percentiel en de trend en p waarde van de trend van koper (mg/kg) van het zwevende stof van de Westerschelde en de monding berekend op alle beschikbare data vanaf 1996.</caption>
<thead>
<tr class="header">
<th align="center">Station</th>
<th align="center">Mediaan</th>
<th align="center">90-perc</th>
<th align="center">10-perc</th>
<th align="center">Trend</th>
<th align="center">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Schaar van Ouden Doel</td>
<td align="center">63</td>
<td align="center">80.0</td>
<td align="center">49.4</td>
<td align="center">-1.150</td>
<td align="center">0.000</td>
</tr>
<tr class="even">
<td align="center">Vlissingen boei SSVH</td>
<td align="center">18</td>
<td align="center">22.9</td>
<td align="center">15.4</td>
<td align="center">-0.042</td>
<td align="center">0.696</td>
</tr>
</tbody>
</table>
<div class="figure" style="text-align: center"><span id="fig:zwevendKoper"></span>
<img src="_main_files/figure-html/zwevendKoper-1.png" alt="Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Koper voor beide stations." width="85%" />
<p class="caption">
Figuur 5.12: Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Koper voor beide stations.
</p>
</div>
</div>
<div id="zwevend-kwik" class="section level3" number="5.3.6">
<h3><span class="header-section-number">5.3.6</span> Kwik</h3>
<p>Figuur <a href="zwevend-stof.html#fig:zwevendKwik">5.13</a> toont het jaargemiddelde kwik per station voor de periode vanaf 1996 t/m 2019, samen met de laagste en de hoogste gemeten waarde per jaar. Daarnaast zijn in Tabel <a href="zwevend-stof.html#tab:zwevendKwikTab">5.8</a> de gemiddelde, minimale en maximale waardes per station weergegeven.</p>
<p>De concentraties kwik in zwevende stof nemen af in stroomafwaartse richting (factor 3). Op beide stations is een dalende trend van 0,01 tot 0,02 mg/kg per jaar aanwezig. Beide trends hebben een hoge statistische correlatie. Dit zijn de grootste correlaties gevonden voor de fyshisch-chemische parameters in zwevende stof.</p>
<table>
<caption><span id="tab:zwevendKwikTab">Tabel 5.8: </span>Jaarlijks mediaan, 10-percentiel en 90-percentiel en de trend en p waarde van de trend van kwik (mg/kg) van het zwevende stof van de Westerschelde en de monding berekend op alle beschikbare data vanaf 1996.</caption>
<thead>
<tr class="header">
<th align="center">Station</th>
<th align="center">Mediaan</th>
<th align="center">90-perc</th>
<th align="center">10-perc</th>
<th align="center">Trend</th>
<th align="center">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Schaar van Ouden Doel</td>
<td align="center">0.71</td>
<td align="center">0.940</td>
<td align="center">0.552</td>
<td align="center">-0.019</td>
<td align="center">0</td>
</tr>
<tr class="even">
<td align="center">Vlissingen boei SSVH</td>
<td align="center">0.24</td>
<td align="center">0.315</td>
<td align="center">0.168</td>
<td align="center">-0.007</td>
<td align="center">0</td>
</tr>
</tbody>
</table>
<div class="figure" style="text-align: center"><span id="fig:zwevendKwik"></span>
<img src="_main_files/figure-html/zwevendKwik-1.png" alt="Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Kwik voor beide stations." width="85%" />
<p class="caption">
Figuur 5.13: Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Kwik voor beide stations.
</p>
</div>
</div>
<div id="zwevend-lood" class="section level3" number="5.3.7">
<h3><span class="header-section-number">5.3.7</span> Lood</h3>
<p>Figuur <a href="zwevend-stof.html#fig:zwevendLood">5.14</a> toont het jaargemiddelde lood per station voor de periode vanaf 1996 t/m 2019, samen met de laagste en de hoogste gemeten waarde per jaar. Daarnaast zijn in Tabel <a href="zwevend-stof.html#tab:zwevendLoodTab">5.9</a> zijn de gemiddelde, minimale en maximale waardes per station weergegeven.</p>
<p>De concentraties lood in zwevende stof nemen af in stroomafwaartse richting (factor 2,3). Bij Schaar van Ouden Doel is een dalende trend aanwezig, maar lijken de meetwaarden de laatste paar jaar stabiel. Bij Vlissingen boei SSVH zijn de gemeten waarden over de beschouwde periode ongeveer constant. De berekende trend over de gehele dataset is echter voor beide negatief (afname). De afname is sterker voor Schaar van Ouden Doel.</p>
<table>
<caption><span id="tab:zwevendLoodTab">Tabel 5.9: </span>Jaarlijks mediaan, 10-percentiel en 90-percentiel en de trend en p waarde van de trend van lood (mg/kg) van het zwevende stof van de Westerschelde en de monding berekend op alle beschikbare data vanaf 1996.</caption>
<thead>
<tr class="header">
<th align="center">Station</th>
<th align="center">Mediaan</th>
<th align="center">90-perc</th>
<th align="center">10-perc</th>
<th align="center">Trend</th>
<th align="center">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Schaar van Ouden Doel</td>
<td align="center">92</td>
<td align="center">125</td>
<td align="center">76.4</td>
<td align="center">-2.310</td>
<td align="center">0</td>
</tr>
<tr class="even">
<td align="center">Vlissingen boei SSVH</td>
<td align="center">43</td>
<td align="center">50</td>
<td align="center">33.9</td>
<td align="center">-0.616</td>
<td align="center">0</td>
</tr>
</tbody>
</table>
<div class="figure" style="text-align: center"><span id="fig:zwevendLood"></span>
<img src="_main_files/figure-html/zwevendLood-1.png" alt="Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Lood voor beide stations." width="85%" />
<p class="caption">
Figuur 5.14: Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Lood voor beide stations.
</p>
</div>
</div>
<div id="zwevend-vanadium" class="section level3" number="5.3.8">
<h3><span class="header-section-number">5.3.8</span> Vanadium</h3>
<p>Figuur <a href="zwevend-stof.html#fig:zwevendVanadium">5.15</a> toont het jaargemiddelde Vanadium per station voor de periode vanaf 2005 t/m 2019, samen met de laagste en de hoogste gemeten waarde per jaar. Daarnaast zijn in Tabel <a href="zwevend-stof.html#tab:zwevendVanadiumTab">5.10</a> de gemiddelde, minimale en maximale waardes per station weergegeven.</p>
<p>De concentraties vanadium in zwevend stof laten geen duidelijke ruimtelijke gradiënt zien. Er lijken weinig veranderingen op de treden. Bij Vlissingen boei SSVH zijn de waarden voor 2012 en 2013 een stuk lager dan de periode daarvoor hetgeen zich uit in een dalende trend van 2,3 mg/kg per jaar met een statistische significantie.</p>
<table>
<caption><span id="tab:zwevendVanadiumTab">Tabel 5.10: </span>Jaarlijks mediaan, 10-percentiel en 90-percentiel en de trend en p waarde van de trend van vanadium (mg/kg) van het zwevende stof van de Westerschelde en de monding berekend op alle beschikbare data vanaf 1996.</caption>
<thead>
<tr class="header">
<th align="center">Station</th>
<th align="center">Mediaan</th>
<th align="center">90-perc</th>
<th align="center">10-perc</th>
<th align="center">Trend</th>
<th align="center">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Schaar van Ouden Doel</td>
<td align="center">83.6</td>
<td align="center">94.0</td>
<td align="center">73.4</td>
<td align="center">-0.58</td>
<td align="center">0.081</td>
</tr>
<tr class="even">
<td align="center">Vlissingen boei SSVH</td>
<td align="center">80.0</td>
<td align="center">99.1</td>
<td align="center">60.7</td>
<td align="center">-1.90</td>
<td align="center">0.000</td>
</tr>
</tbody>
</table>
<div class="figure" style="text-align: center"><span id="fig:zwevendVanadium"></span>
<img src="_main_files/figure-html/zwevendVanadium-1.png" alt="Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Vanadium voor beide stations." width="85%" />
<p class="caption">
Figuur 5.15: Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Vanadium voor beide stations.
</p>
</div>
</div>
<div id="zwevend-zink" class="section level3" number="5.3.9">
<h3><span class="header-section-number">5.3.9</span> Zink</h3>
<p>Figuur <a href="zwevend-stof.html#fig:zwevendZink">5.16</a> toont het jaargemiddelde zink per station voor de periode vanaf 1996 t/m 2019, samen met de laagste en de hoogste gemeten waarde per jaar. Daarnaast zijn in Tabel <a href="zwevend-stof.html#tab:zwevendZinkTab">5.11</a> de gemiddelde, minimale en maximale waardes per station weergegeven.</p>
<p>De concentraties zink in zwevende stof nemen sterk af in stroomafwaartse richting (factor 3,1). Bij beide stations is er een dalende trend die een statistische beperkt correlatie heeft. Bij Schaar van Ouden Doel is deze trend sterker dan bij station Vlissingen, waar de metingen meer constant over tijd zijn.</p>
<table>
<caption><span id="tab:zwevendZinkTab">Tabel 5.11: </span>Jaarlijks mediaan, 10-percentiel en 90-percentiel en de trend en p waarde van de trend van zink (mg/kg) van het zwevende stof van de Westerschelde en de monding berekend op alle beschikbare data vanaf 1996.</caption>
<thead>
<tr class="header">
<th align="center">Station</th>
<th align="center">Mediaan</th>
<th align="center">90-perc</th>
<th align="center">10-perc</th>
<th align="center">Trend</th>
<th align="center">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Schaar van Ouden Doel</td>
<td align="center">390</td>
<td align="center">483</td>
<td align="center">330</td>
<td align="center">-5.23</td>
<td align="center">0</td>
</tr>
<tr class="even">
<td align="center">Vlissingen boei SSVH</td>
<td align="center">130</td>
<td align="center">150</td>
<td align="center">115</td>
<td align="center">-1.33</td>
<td align="center">0</td>
</tr>
</tbody>
</table>
<div class="figure" style="text-align: center"><span id="fig:zwevendZink"></span>
<img src="_main_files/figure-html/zwevendZink-1.png" alt="Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Zink voor beide stations." width="85%" />
<p class="caption">
Figuur 5.16: Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Zink voor beide stations.
</p>
</div>
</div>
</div>
<div id="zwevend-PAK" class="section level2" number="5.4">
<h2><span class="header-section-number">5.4</span> Polycyclische aromatische koolwaterstoffen (PAK’s)</h2>
<p>In deze paragraaf presenteren we de concentraties in zwevend stof van de volgende polycyclische aromatische koolwaterstoffen:</p>
<ul>
<li>Antraceen (Figuur <a href="zwevend-stof.html#fig:zwevendAntraceen">5.17</a>)</li>
<li>Benzo[<em>a</em>]antraceen (Figuur <a href="zwevend-stof.html#fig:zwevendBenzoaantraceen">5.20</a>)</li>
<li>Benzo[<em>a</em>]pyreen (Figuur <a href="zwevend-stof.html#fig:zwevendBenzoapyreen">5.18</a>)</li>
<li>Benzo[<em>g,h,i</em>]peryleen (Figuur <a href="zwevend-stof.html#fig:zwevendBenzoghiperyleen">5.19</a>)</li>
<li>Benzo[<em>k</em>]fluorantheen (Figuur <a href="#fig:zwevendBenzokfluorantheen"><strong>??</strong></a>)</li>
<li>Chryseen (Figuur <a href="zwevend-stof.html#fig:zwevendChryseen">5.21</a>)</li>
<li>Fenanthreen (Figuur <a href="zwevend-stof.html#fig:zwevendFenanthreen">5.22</a>)</li>
<li>Fluorantheen (Figuur <a href="zwevend-stof.html#fig:zwevendFluorantheen">5.23</a>)</li>
<li>Indeno[<em>1,2,3-c,d</em>]pyreen (Figuur <a href="zwevend-stof.html#fig:zwevendIndeno">5.24</a>)</li>
<li>Naftaleen (Figuur <a href="zwevend-stof.html#fig:zwevendNaftaleen">5.25</a>)</li>
</ul>
<p>Polycyclische aromatische koolwaterstoffen (PAK’s) zijn organische verbindingen die bestaan uit gekoppelde aromatische ringen (bijvoorbeeld benzeenringen) maar geen heteroatomen of functionele groepen bevatten. PAK’s ontstaan bij onvolledige verbranding of verkoling van diverse koolstof bevattende materialen (<span class="citation">@W1989</span>).</p>
<p>Voor alle getoonde PAK’s is er een duidelijke ruimtelijke gradiënt waarneembaar, met hogere concentraties bij Schaar van Ouden Doel en lagere concentraties bij Vlissingen boei SSVH. De verschillen tussen de minimale en maximale waarde zijn bij Schaar van Ouden Doel groter dan bij Vlissingen boei SSVH. Daarnaast is er in alle/veel gevallen een dalende trend zichtbaar, die het sterkst is bij Schaar van Ouden Doel. De meetreeksen bevatten enkele waarden die onder de detectiegrens vallen, waardoor de gemiddelden (en minima) wat hoger zijn uitgevallen.</p>
<div id="zwevend-antraceen" class="section level3" number="5.4.1">
<h3><span class="header-section-number">5.4.1</span> Antraceen</h3>
<p>Figuur <a href="zwevend-stof.html#fig:zwevendAntraceen">5.17</a> toont het jaargemiddelde antraceen per station voor de periode vanaf 1996 t/m 2019, samen met de laagste en de hoogste gemeten waarde per jaar. Daarnaast zijn in Tabel <a href="zwevend-stof.html#tab:zwevendAntraceenTab">5.12</a> de gemiddelde, minimale en maximale waardes per station weergegeven. Beide stations hebben een afnemende trend. Voor Schaar van Ouden Doel is de trend sterker en statistisch significanter. In 2019 zien we echter een relatief sterke toename in de jaargemiddeldes van antraceen.</p>
<table>
<caption><span id="tab:zwevendAntraceenTab">Tabel 5.12: </span>Jaarlijks mediaan, 10-percentiel en 90-percentiel en de trend en p waarde van de trend van antraceen (mg/kg) van het zwevende stof van de Westerschelde en de monding berekend op alle beschikbare data vanaf 1996.</caption>
<thead>
<tr class="header">
<th align="center">Station</th>
<th align="center">Mediaan</th>
<th align="center">90-perc</th>
<th align="center">10-perc</th>
<th align="center">Trend</th>
<th align="center">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Schaar van Ouden Doel</td>
<td align="center">0.136</td>
<td align="center">0.190</td>
<td align="center">0.070</td>
<td align="center">-0.006</td>
<td align="center">0.000</td>
</tr>
<tr class="even">
<td align="center">Vlissingen boei SSVH</td>
<td align="center">0.027</td>
<td align="center">0.033</td>
<td align="center">0.022</td>
<td align="center">0.000</td>
<td align="center">0.089</td>
</tr>
</tbody>
</table>
<div class="figure" style="text-align: center"><span id="fig:zwevendAntraceen"></span>
<img src="_main_files/figure-html/zwevendAntraceen-1.png" alt="Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Antraceen voor beide stations." width="85%" />
<p class="caption">
Figuur 5.17: Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Antraceen voor beide stations.
</p>
</div>
</div>
<div id="zwevend-Benzoapyreen" class="section level3" number="5.4.2">
<h3><span class="header-section-number">5.4.2</span> Benzo[<em>a</em>]pyreen</h3>
<!-- \subsection {\texorpdfstring{Benzo[\textit{a}]pyreen}{Benzo[\textit{a}]pyreen}}  -->
<p>Figuur <a href="zwevend-stof.html#fig:zwevendBenzoapyreen">5.18</a> toont het jaargemiddelde Benzo[<em>a</em>]pyreen per station voor de periode vanaf 1996 t/m 2019, samen met de laagste en de hoogste gemeten waarde per jaar. Daarnaast zijn in Tabel <a href="zwevend-stof.html#tab:zwevendBenzoapyreenTab">5.13</a> de gemiddelde, minimale en maximale waardes per station weergegeven. Beide stations hebben een afnemende trend. Voor Schaar van Ouden Doel is de trend sterker en statistisch significanter.</p>
<table>
<caption><span id="tab:zwevendBenzoapyreenTab">Tabel 5.13: </span>Jaarlijks mediaan, 10-percentiel en 90-percentiel en de trend en p waarde van de trend van benzo(a)pyreen (mg/kg) van het zwevende stof van de Westerschelde en de monding berekend op alle beschikbare data vanaf 1996.</caption>
<thead>
<tr class="header">
<th align="center">Station</th>
<th align="center">Mediaan</th>
<th align="center">90-perc</th>
<th align="center">10-perc</th>
<th align="center">Trend</th>
<th align="center">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Schaar van Ouden Doel</td>
<td align="center">0.410</td>
<td align="center">0.52</td>
<td align="center">0.250</td>
<td align="center">-0.013</td>
<td align="center">0.000</td>
</tr>
<tr class="even">
<td align="center">Vlissingen boei SSVH</td>
<td align="center">0.087</td>
<td align="center">0.11</td>
<td align="center">0.072</td>
<td align="center">-0.001</td>
<td align="center">0.002</td>
</tr>
</tbody>
</table>
<div class="figure" style="text-align: center"><span id="fig:zwevendBenzoapyreen"></span>
<img src="_main_files/figure-html/zwevendBenzoapyreen-1.png" alt="Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Benzoapyreen voor beide stations." width="85%" />
<p class="caption">
Figuur 5.18: Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Benzoapyreen voor beide stations.
</p>
</div>
</div>
<div id="zwevend-Benzoghiperyleen" class="section level3" number="5.4.3">
<h3><span class="header-section-number">5.4.3</span> Benzo[<em>g,h,i</em>]peryleen</h3>
<!-- \subsection {\texorpdfstring{Benzo[\textit{g,h,i}]peryleen}{Benzo[\textit{g,h,i}]peryleen}}  -->
<p>Figuur <a href="zwevend-stof.html#fig:zwevendBenzoghiperyleen">5.19</a> toont het jaargemiddelde Benzo[<em>g,h,i</em>]peryleen per station voor de periode vanaf 1996 t/m 2019, samen met de laagste en de hoogste gemeten waarde per jaar. Daarnaast zijn in Tabel <a href="zwevend-stof.html#tab:zwevendBenzoghiperyleenTab">5.14</a> de gemiddelde, minimale en maximale waardes per station weergegeven. Schaal van Ouden Doel heeft hogere waardes benzoperyleen in zwevend stof vergeleken met Vlissingen. Beide stations hebben een afnemende trend, hoewel de trend en de correlatie verschilt per station.</p>
<table>
<caption><span id="tab:zwevendBenzoghiperyleenTab">Tabel 5.14: </span>Jaarlijks mediaan, 10-percentiel en 90-percentiel en de trend en p waarde van de trend van benzo(g,h,i)peryleen (mg/kg) van het zwevende stof van de Westerschelde en de monding berekend op alle beschikbare data vanaf 1996.</caption>
<thead>
<tr class="header">
<th align="center">Station</th>
<th align="center">Mediaan</th>
<th align="center">90-perc</th>
<th align="center">10-perc</th>
<th align="center">Trend</th>
<th align="center">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Schaar van Ouden Doel</td>
<td align="center">0.330</td>
<td align="center">0.43</td>
<td align="center">0.220</td>
<td align="center">-0.007</td>
<td align="center">0.000</td>
</tr>
<tr class="even">
<td align="center">Vlissingen boei SSVH</td>
<td align="center">0.091</td>
<td align="center">0.11</td>
<td align="center">0.072</td>
<td align="center">-0.001</td>
<td align="center">0.003</td>
</tr>
</tbody>
</table>
<div class="figure" style="text-align: center"><span id="fig:zwevendBenzoghiperyleen"></span>
<img src="_main_files/figure-html/zwevendBenzoghiperyleen-1.png" alt="Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Benzoperyleen voor beide stations." width="85%" />
<p class="caption">
Figuur 5.19: Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Benzoperyleen voor beide stations.
</p>
</div>
</div>
<div id="zwevend-Benzoaantraceen" class="section level3" number="5.4.4">
<h3><span class="header-section-number">5.4.4</span> Benzo[<em>a</em>]antraceen</h3>
<!-- \subsection {\texorpdfstring{Benzo[\textit{a}]antraceen}{Benzo[\textit{a}]antraceen}} -->
<p>Figuur <a href="zwevend-stof.html#fig:zwevendBenzoaantraceen">5.20</a> toont het jaargemiddelde Benzo[<em>a</em>]antraceen per station voor de periode vanaf 1996 t/m 2019, samen met de laagste en de hoogste gemeten waarde per jaar. Daarnaast zijn in Tabel <a href="zwevend-stof.html#tab:zwevendBenzoaantraceenTab">5.15</a> de gemiddelde, minimale en maximale waardes per station weergegeven. Schaal van Ouden Doel heeft hogere waardes Benzo[<em>a</em>]antraceen in zwevend stof vergeleken met Vlissingen. Beide stations hebben een afnemende trend, hoewel de trend en de correlatie verschilt per station.</p>
<table>
<caption><span id="tab:zwevendBenzoaantraceenTab">Tabel 5.15: </span>Jaarlijks mediaan, 10-percentiel en 90-percentiel en de trend en p waarde van de trend van benzo(a)antraceen (mg/kg) van het zwevende stof van de Westerschelde en de monding berekend op alle beschikbare data vanaf 1996.</caption>
<thead>
<tr class="header">
<th align="center">Station</th>
<th align="center">Mediaan</th>
<th align="center">90-perc</th>
<th align="center">10-perc</th>
<th align="center">Trend</th>
<th align="center">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Schaar van Ouden Doel</td>
<td align="center">0.300</td>
<td align="center">0.410</td>
<td align="center">0.200</td>
<td align="center">-0.008</td>
<td align="center">0</td>
</tr>
<tr class="even">
<td align="center">Vlissingen boei SSVH</td>
<td align="center">0.072</td>
<td align="center">0.091</td>
<td align="center">0.059</td>
<td align="center">-0.001</td>
<td align="center">0</td>
</tr>
</tbody>
</table>
<div class="figure" style="text-align: center"><span id="fig:zwevendBenzoaantraceen"></span>
<img src="_main_files/figure-html/zwevendBenzoaantraceen-1.png" alt="Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Benzoaantraceen voor beide stations." width="85%" />
<p class="caption">
Figuur 5.20: Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Benzoaantraceen voor beide stations.
</p>
</div>
</div>
<div id="zwevend-Benzokfluorantheen" class="section level3" number="5.4.5">
<h3><span class="header-section-number">5.4.5</span> Benzo[<em>k</em>]fluorantheen</h3>
<!-- \subsection {\texorpdfstring{Benzo[\textit{k}]fluorantheen}{Benzo[\textit{k}]fluorantheen}} -->
<p>Figuur <a href="#fig:zwevendBenzokfluorantheen"><strong>??</strong></a> toont het jaargemiddelde Benzo[<em>k</em>]fluorantheen per station voor de periode vanaf 1996 t/m 2019, samen met de laagste en de hoogste gemeten waarde per jaar. Daarnaast zijn in Tabel <a href="zwevend-stof.html#tab:zwevendBenzokfluorantheenTab">5.16</a> de gemiddelde, minimale en maximale waardes per station weergegeven. Schaal van Ouden Doel heeft hogere waardes Benzo[<em>k</em>]fluorantheen in zwevend stof vergeleken met Vlissingen en daarnaast neemt deze hoeveelheid sterker af bij Schaar van Ouden Doel. Voor beide stations is deze afnemende trend statistisch significant (R van 0,55 - 0,95). De concentraties bij Vlissingen zijn echter sinds 2016 wel iets toegenomen. Hierdoor is de significantie van de trend ten opzichte van voor 2016 dan ook afgenomen.</p>
<p><em>In 2019 is het gemiddelde en maximum bij Vlissingen boei SSVH erg hoog. Dit lijkt op een verkeerde meting, hiaat of een FillValue. In een volgende versie van het rapport zullen we dit uitgezocht hebben.</em></p>
<table>
<caption><span id="tab:zwevendBenzokfluorantheenTab">Tabel 5.16: </span>Jaarlijks mediaan, 10-percentiel en 90-percentiel en de trend en p waarde van de trend van benzo(k)fluorantheen (mg/kg) van het zwevende stof van de Westerschelde en de monding berekend op alle beschikbare data vanaf 1996.</caption>
<colgroup>
<col width="100%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Er zijn geen data gevonden voor Benzo(k)fluorantheen in mg/kg drooggewicht in zwevend stof</td>
</tr>
</tbody>
</table>
<pre><code>## [1] &quot;Er zijn geen data gevonden voor Benzo(k)fluorantheen in mg/kg drooggewicht in zwevend stof&quot;</code></pre>
</div>
<div id="zwevend-chryseen" class="section level3" number="5.4.6">
<h3><span class="header-section-number">5.4.6</span> Chryseen</h3>
<p>Figuur <a href="zwevend-stof.html#fig:zwevendChryseen">5.21</a> toont het jaargemiddelde chryseen per station voor de periode vanaf 1996 t/m 2019, samen met de laagste en de hoogste gemeten waarde per jaar. Daarnaast zijn in Tabel <a href="zwevend-stof.html#tab:zwevendChryseenTab">5.17</a> de gemiddelde, minimale en maximale waardes per station weergegeven. Beide stations hebben een afnemende trend, hoewel de trend en de correlatie verschilt per station.</p>
<table>
<caption><span id="tab:zwevendChryseenTab">Tabel 5.17: </span>Jaarlijks mediaan, 10-percentiel en 90-percentiel en de trend en p waarde van de trend van chryseen (mg/kg) van het zwevende stof van de Westerschelde en de monding berekend op alle beschikbare data vanaf 1996.</caption>
<thead>
<tr class="header">
<th align="center">Station</th>
<th align="center">Mediaan</th>
<th align="center">90-perc</th>
<th align="center">10-perc</th>
<th align="center">Trend</th>
<th align="center">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Schaar van Ouden Doel</td>
<td align="center">0.320</td>
<td align="center">0.440</td>
<td align="center">0.220</td>
<td align="center">-0.007</td>
<td align="center">0.000</td>
</tr>
<tr class="even">
<td align="center">Vlissingen boei SSVH</td>
<td align="center">0.074</td>
<td align="center">0.096</td>
<td align="center">0.061</td>
<td align="center">-0.001</td>
<td align="center">0.015</td>
</tr>
</tbody>
</table>
<div class="figure" style="text-align: center"><span id="fig:zwevendChryseen"></span>
<img src="_main_files/figure-html/zwevendChryseen-1.png" alt="Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Chryseen voor beide stations." width="85%" />
<p class="caption">
Figuur 5.21: Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Chryseen voor beide stations.
</p>
</div>
</div>
<div id="zwevend-fenanthreen" class="section level3" number="5.4.7">
<h3><span class="header-section-number">5.4.7</span> Fenanthreen</h3>
<p>Figuur <a href="zwevend-stof.html#fig:zwevendFenanthreen">5.22</a> toont het jaargemiddelde fenanthreen per station voor de periode vanaf 1996 t/m 2019, samen met de laagste en de hoogste gemeten waarde per jaar. Daarnaast zijn in Tabel <a href="zwevend-stof.html#tab:zwevendFenanthreenTab">5.18</a> de gemiddelde, minimale en maximale waardes per station weergegeven. Beide stations hebben een afnemende trend, hoewel de trend en de correlatie verschilt per station.</p>
<table>
<caption><span id="tab:zwevendFenanthreenTab">Tabel 5.18: </span>Jaarlijks mediaan, 10-percentiel en 90-percentiel en de trend en p waarde van de trend van fenanthreen (mg/kg) van het zwevende stof van de Westerschelde en de monding berekend op alle beschikbare data vanaf 1996.</caption>
<thead>
<tr class="header">
<th align="center">Station</th>
<th align="center">Mediaan</th>
<th align="center">90-perc</th>
<th align="center">10-perc</th>
<th align="center">Trend</th>
<th align="center">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Schaar van Ouden Doel</td>
<td align="center">0.35</td>
<td align="center">0.52</td>
<td align="center">0.22</td>
<td align="center">-0.008</td>
<td align="center">0.011</td>
</tr>
<tr class="even">
<td align="center">Vlissingen boei SSVH</td>
<td align="center">0.10</td>
<td align="center">0.13</td>
<td align="center">0.08</td>
<td align="center">-0.001</td>
<td align="center">0.196</td>
</tr>
</tbody>
</table>
<div class="figure" style="text-align: center"><span id="fig:zwevendFenanthreen"></span>
<img src="_main_files/figure-html/zwevendFenanthreen-1.png" alt="Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Fenanthreen voor beide stations." width="85%" />
<p class="caption">
Figuur 5.22: Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Fenanthreen voor beide stations.
</p>
</div>
</div>
<div id="zwevend-fluorantheen" class="section level3" number="5.4.8">
<h3><span class="header-section-number">5.4.8</span> Fluorantheen</h3>
<p>Figuur <a href="zwevend-stof.html#fig:zwevendFluorantheen">5.23</a> toont het jaargemiddelde fluorantheen per station voor de periode vanaf 1996 t/m 2019, samen met de laagste en de hoogste gemeten waarde per jaar. Daarnaast zijn in Tabel <a href="zwevend-stof.html#tab:zwevendFluorantheenTab">5.19</a> de gemiddelde, minimale en maximale waardes per station weergegeven. Beide stations constateren we een afnemende trend, hoewel Vlissingen boei SSHV net significant.</p>
<table>
<caption><span id="tab:zwevendFluorantheenTab">Tabel 5.19: </span>Jaarlijks mediaan, 10-percentiel en 90-percentiel en de trend en p waarde van de trend van fluorantheen (mg/kg) van het zwevende stof van de Westerschelde en de monding berekend op alle beschikbare data vanaf 1996.</caption>
<thead>
<tr class="header">
<th align="center">Station</th>
<th align="center">Mediaan</th>
<th align="center">90-perc</th>
<th align="center">10-perc</th>
<th align="center">Trend</th>
<th align="center">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Schaar van Ouden Doel</td>
<td align="center">0.59</td>
<td align="center">0.883</td>
<td align="center">0.390</td>
<td align="center">-0.018</td>
<td align="center">0</td>
</tr>
<tr class="even">
<td align="center">Vlissingen boei SSVH</td>
<td align="center">0.16</td>
<td align="center">0.210</td>
<td align="center">0.135</td>
<td align="center">-0.002</td>
<td align="center">0</td>
</tr>
</tbody>
</table>
<div class="figure" style="text-align: center"><span id="fig:zwevendFluorantheen"></span>
<img src="_main_files/figure-html/zwevendFluorantheen-1.png" alt="Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Fluorantheen voor beide stations." width="85%" />
<p class="caption">
Figuur 5.23: Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Fluorantheen voor beide stations.
</p>
</div>
</div>
<div id="zwevend-indeno" class="section level3" number="5.4.9">
<h3><span class="header-section-number">5.4.9</span> Indeno[<em>1,2,3-c,d</em>]pyreen</h3>
<!-- \subsection {\texorpdfstring{Indeno[\textit{1,2,3-c,d}]pyreen}{Indeno[\textit{1,2,3-c,d}]pyreen}}  -->
<p>Figuur <a href="zwevend-stof.html#fig:zwevendIndeno">5.24</a> toont het jaargemiddelde Indeno[]pyreen per station voor de periode vanaf 1996 t/m 2019, samen met de laagste en de hoogste gemeten waarde per jaar. Daarnaast zijn in Tabel <a href="zwevend-stof.html#tab:zwevendIndenoTab">5.20</a> de gemiddelde, minimale en maximale waardes per station weergegeven. Deze neemt statistisch significant af bij Schaar van Ouden Doel.</p>
<table>
<caption><span id="tab:zwevendIndenoTab">Tabel 5.20: </span>Jaarlijks mediaan, 10-percentiel en 90-percentiel en de trend en p waarde van de trend van indeno(1,2,3-c,d)pyreen (mg/kg) van het zwevende stof van de Westerschelde en de monding berekend op alle beschikbare data vanaf 1996.</caption>
<thead>
<tr class="header">
<th align="center">Station</th>
<th align="center">Mediaan</th>
<th align="center">90-perc</th>
<th align="center">10-perc</th>
<th align="center">Trend</th>
<th align="center">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Schaar van Ouden Doel</td>
<td align="center">0.38</td>
<td align="center">0.49</td>
<td align="center">0.240</td>
<td align="center">-0.011</td>
<td align="center">0.000</td>
</tr>
<tr class="even">
<td align="center">Vlissingen boei SSVH</td>
<td align="center">0.10</td>
<td align="center">0.13</td>
<td align="center">0.085</td>
<td align="center">-0.001</td>
<td align="center">0.006</td>
</tr>
</tbody>
</table>
<div class="figure" style="text-align: center"><span id="fig:zwevendIndeno"></span>
<img src="_main_files/figure-html/zwevendIndeno-1.png" alt="Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Indeno[*1,2,3-c,d*]pyreen voor beide stations." width="85%" />
<p class="caption">
Figuur 5.24: Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Indeno[<em>1,2,3-c,d</em>]pyreen voor beide stations.
</p>
</div>
</div>
<div id="zwevend-naftaleen" class="section level3" number="5.4.10">
<h3><span class="header-section-number">5.4.10</span> Naftaleen</h3>
<p>Figuur <a href="zwevend-stof.html#fig:zwevendNaftaleen">5.25</a> toont het jaargemiddelde naftaleen per station voor de periode vanaf 1996 t/m 2019, samen met de laagste en de hoogste gemeten waarde per jaar. Daarnaast zijn in Tabel <a href="zwevend-stof.html#tab:zwevendNaftaleenTab">5.21</a> de gemiddelde, minimale en maximale waardes per station weergegeven. We constateren geen temporale trend.</p>
<table>
<caption><span id="tab:zwevendNaftaleenTab">Tabel 5.21: </span>Jaarlijks mediaan, 10-percentiel en 90-percentiel en de trend en p waarde van de trend van naftaleen (mg/kg) van het zwevende stof van de Westerschelde en de monding berekend op alle beschikbare data vanaf 1996.</caption>
<thead>
<tr class="header">
<th align="center">Station</th>
<th align="center">Mediaan</th>
<th align="center">90-perc</th>
<th align="center">10-perc</th>
<th align="center">Trend</th>
<th align="center">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Schaar van Ouden Doel</td>
<td align="center">0.17</td>
<td align="center">0.25</td>
<td align="center">0.07</td>
<td align="center">0</td>
<td align="center">0.924</td>
</tr>
</tbody>
</table>
<div class="figure" style="text-align: center"><span id="fig:zwevendNaftaleen"></span>
<img src="_main_files/figure-html/zwevendNaftaleen-1.png" alt="Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Naftaleen voor beide stations." width="85%" />
<p class="caption">
Figuur 5.25: Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Naftaleen voor beide stations.
</p>
</div>
</div>
</div>
<div id="zwevend-PCB" class="section level2" number="5.5">
<h2><span class="header-section-number">5.5</span> Polychloorbifenylen (PCB’s)</h2>
<p>In deze paragraaf presenteren we de gemeten gehalten van de volgende PCB’s in zwevende stof:</p>
<ul>
<li>2,2’,3,4,4’,5,5’-heptachloorbifenyl (PCB180, Figuur <a href="zwevend-stof.html#fig:zwevendPCB180">5.26</a>)</li>
<li>2,2’,3,4,4’,5’-hexachloorbifenyl (PCB138, Figuur <a href="zwevend-stof.html#fig:zwevendPCB138">5.27</a>)</li>
<li>2,2’,4,4’,5,5’-hexachloorbifenyl (PCB153, Figuur <a href="zwevend-stof.html#fig:zwevendPCB153">5.28</a>)</li>
<li>2,2’,4,5,5’-pentachloorbifenyl (PCB101, Figuur <a href="zwevend-stof.html#fig:zwevendPCB101">5.29</a>)</li>
<li>2,2’,5,5’-tetrachloorbifenyl (PCB52, Figuur <a href="zwevend-stof.html#fig:zwevendPCB52">5.30</a>)</li>
<li>2,3’,4,4’,5-pentachloorbifenyl (PCB118, Figuur <a href="zwevend-stof.html#fig:zwevendPCB118">5.31</a>)</li>
<li>2,4,4’-trichloorbifenyl (PCB28, Figuur <a href="zwevend-stof.html#fig:zwevendPCB28">5.32</a>)</li>
</ul>
<p>Polychloorbifenylen (PCB’s) zijn vanaf 1930 op grote schaal toegepast in industrie en techniek. Sinds de jaren 70 is duidelijk geworden dat PCB’s het milieu en in het bijzonder de fauna sterk verontreinigen. Dit houdt de grootste risico’s in voor dieren die aan het eind van een voedselketen staan en vis consumeren. (Bron: <a href="http://www.chemischefeitelijkheden.nl/Uploads/Magazines/h012.pdf" class="uri">http://www.chemischefeitelijkheden.nl/Uploads/Magazines/h012.pdf</a>).</p>
<p>Voor alle getoonde PCB’s is er een duidelijke ruimtelijke gradiënt waarneembaar, met hogere concentraties bij Schaar van Ouden Doel en lagere concentraties bij Vlissingen boei SSVH. Daarnaast is er in alle/veel gevallen een dalende trend zichtbaar, die het sterkst is bij Schaar van Ouden Doel. De meetreeksen bevatten enkele waarden die onder de detectiegrens vallen, waardoor de gemiddelden (en minima) wat hoger zijn uitgevallen.</p>
<div id="zwevend-PCB180" class="section level3" number="5.5.1">
<h3><span class="header-section-number">5.5.1</span> PCB180</h3>
<p>Figuur <a href="zwevend-stof.html#fig:zwevendPCB180">5.26</a> toont het jaargemiddelde PCB180 per station voor de periode vanaf 1996 t/m 2019, samen met de laagste en de hoogste gemeten waarde per jaar. Daarnaast zijn in Tabel <a href="zwevend-stof.html#tab:zwevendPCB180Tab">5.22</a> de gemiddelde, minimale en maximale waardes per station weergegeven. Voor beide stations constateren we een afnemende lineaire trend rond de 0,06 tot 0,26 <span class="math inline">\(\mu\)</span>g/kg per jaar. Voor station Vlissingen is deze afname minder groot dan voor station Schaar van Ouden Doel, maar deze trend heeft wel een hogere correlatie coëfficiënt.</p>
<table>
<caption><span id="tab:zwevendPCB180Tab">Tabel 5.22: </span>Jaarlijks mediaan, 10-percentiel en 90-percentiel en de trend en p waarde van de trend van PCB180 (ug/kg) van het zwevende stof van de Westerschelde en de monding berekend op alle beschikbare data vanaf 1996.</caption>
<thead>
<tr class="header">
<th align="center">Station</th>
<th align="center">Mediaan</th>
<th align="center">90-perc</th>
<th align="center">10-perc</th>
<th align="center">Trend</th>
<th align="center">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Schaar van Ouden Doel</td>
<td align="center">14.00</td>
<td align="center">18.0</td>
<td align="center">9.000</td>
<td align="center">-0.197</td>
<td align="center">0.013</td>
</tr>
<tr class="even">
<td align="center">Vlissingen boei SSVH</td>
<td align="center">1.04</td>
<td align="center">1.6</td>
<td align="center">0.646</td>
<td align="center">-0.045</td>
<td align="center">0.000</td>
</tr>
</tbody>
</table>
<div class="figure" style="text-align: center"><span id="fig:zwevendPCB180"></span>
<img src="_main_files/figure-html/zwevendPCB180-1.png" alt="Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van PCB180 voor beide stations." width="85%" />
<p class="caption">
Figuur 5.26: Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van PCB180 voor beide stations.
</p>
</div>
</div>
<div id="zwevend-PCB138" class="section level3" number="5.5.2">
<h3><span class="header-section-number">5.5.2</span> PCB138</h3>
<p>Figuur <a href="zwevend-stof.html#fig:zwevendPCB138">5.27</a> toont het jaargemiddelde PCB138 per station voor de periode vanaf 1996 t/m 2019, samen met de laagste en de hoogste gemeten waarde per jaar. Daarnaast zijn in Tabel <a href="zwevend-stof.html#tab:zwevendPCB138Tab">5.23</a> de gemiddelde, minimale en maximale waardes per station weergegeven. Voor beide stations constateren we een afnemende lineaire trend rond de 0,10 tot 0,59 <span class="math inline">\(\mu\)</span>g/kg per jaar. Voor station Vlissingen is de correlatie coëfficient lager.</p>
<table>
<caption><span id="tab:zwevendPCB138Tab">Tabel 5.23: </span>Jaarlijks mediaan, 10-percentiel en 90-percentiel en de trend en p waarde van de trend van PCB138 (ug/kg) van het zwevende stof van de Westerschelde en de monding berekend op alle beschikbare data vanaf 1996.</caption>
<thead>
<tr class="header">
<th align="center">Station</th>
<th align="center">Mediaan</th>
<th align="center">90-perc</th>
<th align="center">10-perc</th>
<th align="center">Trend</th>
<th align="center">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Schaar van Ouden Doel</td>
<td align="center">16.00</td>
<td align="center">22.00</td>
<td align="center">11.000</td>
<td align="center">-0.314</td>
<td align="center">0</td>
</tr>
<tr class="even">
<td align="center">Vlissingen boei SSVH</td>
<td align="center">1.46</td>
<td align="center">2.65</td>
<td align="center">0.964</td>
<td align="center">-0.080</td>
<td align="center">0</td>
</tr>
</tbody>
</table>
<div class="figure" style="text-align: center"><span id="fig:zwevendPCB138"></span>
<img src="_main_files/figure-html/zwevendPCB138-1.png" alt="Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van PCB138 voor beide stations." width="85%" />
<p class="caption">
Figuur 5.27: Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van PCB138 voor beide stations.
</p>
</div>
</div>
<div id="zwevend-PCB153" class="section level3" number="5.5.3">
<h3><span class="header-section-number">5.5.3</span> PCB153</h3>
<p>Figuur <a href="zwevend-stof.html#fig:zwevendPCB153">5.28</a> toont het jaargemiddelde PCB153 per station voor de periode vanaf 1996 t/m 2019, samen met de laagste en de hoogste gemeten waarde per jaar. Daarnaast zijn in Tabel <a href="zwevend-stof.html#tab:zwevendPCB153Tab">5.24</a> de gemiddelde, minimale en maximale waardes per station weergegeven.</p>
<p>Bij station Schaar van Ouden Doel constateren we een afnemende trend met een hoge correlatie. Voor Vlissingen is er een lagere statistische afnemende lineaire trend van 0,1 <span class="math inline">\(\mu\)</span>g/kg per jaar. Dit komt door de relatief hoge waardes in 2003 en 2008.</p>
<table>
<caption><span id="tab:zwevendPCB153Tab">Tabel 5.24: </span>Jaarlijks mediaan, 10-percentiel en 90-percentiel en de trend en p waarde van de trend van PCB153 (ug/kg) van het zwevende stof van de Westerschelde en de monding berekend op alle beschikbare data vanaf 1996.</caption>
<thead>
<tr class="header">
<th align="center">Station</th>
<th align="center">Mediaan</th>
<th align="center">90-perc</th>
<th align="center">10-perc</th>
<th align="center">Trend</th>
<th align="center">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Schaar van Ouden Doel</td>
<td align="center">22.0</td>
<td align="center">27.00</td>
<td align="center">14.00</td>
<td align="center">-0.333</td>
<td align="center">0.016</td>
</tr>
<tr class="even">
<td align="center">Vlissingen boei SSVH</td>
<td align="center">2.3</td>
<td align="center">3.32</td>
<td align="center">1.52</td>
<td align="center">-0.082</td>
<td align="center">0.000</td>
</tr>
</tbody>
</table>
<div class="figure" style="text-align: center"><span id="fig:zwevendPCB153"></span>
<img src="_main_files/figure-html/zwevendPCB153-1.png" alt="Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van PCB153 voor beide stations." width="85%" />
<p class="caption">
Figuur 5.28: Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van PCB153 voor beide stations.
</p>
</div>
</div>
<div id="zwevend-PCB101" class="section level3" number="5.5.4">
<h3><span class="header-section-number">5.5.4</span> PCB101</h3>
<p>Figuur <a href="zwevend-stof.html#fig:zwevendPCB101">5.29</a> toont het jaargemiddelde PCB101 per station voor de periode vanaf 1996 t/m 2019, samen met de laagste en de hoogste gemeten waarde per jaar. Daarnaast zijn in Tabel <a href="zwevend-stof.html#tab:zwevendPCB101Tab">5.25</a> de gemiddelde, minimale en maximale waardes per station weergegeven. Voor beide stations constateren we een afnemende lineaire trend rond de 0,06 tot 0,38 <span class="math inline">\(\mu\)</span>g/kg per jaar. Voor station Vlissingen is deze afname minder groot dan voor station Schaar van Ouden Doel.</p>
<table>
<caption><span id="tab:zwevendPCB101Tab">Tabel 5.25: </span>Jaarlijks mediaan, 10-percentiel en 90-percentiel en de trend en p waarde van de trend van PCB101 (ug/kg) van het zwevende stof van de Westerschelde en de monding berekend op alle beschikbare data vanaf 1996.</caption>
<thead>
<tr class="header">
<th align="center">Station</th>
<th align="center">Mediaan</th>
<th align="center">90-perc</th>
<th align="center">10-perc</th>
<th align="center">Trend</th>
<th align="center">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Schaar van Ouden Doel</td>
<td align="center">11.00</td>
<td align="center">15.0</td>
<td align="center">7.000</td>
<td align="center">-0.258</td>
<td align="center">0</td>
</tr>
<tr class="even">
<td align="center">Vlissingen boei SSVH</td>
<td align="center">1.23</td>
<td align="center">1.9</td>
<td align="center">0.786</td>
<td align="center">-0.045</td>
<td align="center">0</td>
</tr>
</tbody>
</table>
<div class="figure" style="text-align: center"><span id="fig:zwevendPCB101"></span>
<img src="_main_files/figure-html/zwevendPCB101-1.png" alt="Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van PCB101 voor beide stations." width="85%" />
<p class="caption">
Figuur 5.29: Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van PCB101 voor beide stations.
</p>
</div>
</div>
<div id="zwevend-PCB52" class="section level3" number="5.5.5">
<h3><span class="header-section-number">5.5.5</span> PCB52</h3>
<p>Figuur <a href="zwevend-stof.html#fig:zwevendPCB52">5.30</a> toont het jaargemiddelde PCB52 per station voor de periode vanaf 1996 t/m 2019, samen met de laagste en de hoogste gemeten waarde per jaar. Daarnaast zijn in Tabel <a href="zwevend-stof.html#tab:zwevendPCB52Tab">5.26</a> de gemiddelde, minimale en maximale waardes per station weergegeven. Voor Schaar van Ouden Doel constateren we een afnemende lineaire trend van 0,20 <span class="math inline">\(\mu\)</span>g/kg per jaar die beperkt statistisch significant te noemen is. Er is geen significante trend bij Vlissingen.</p>
<table>
<caption><span id="tab:zwevendPCB52Tab">Tabel 5.26: </span>Jaarlijks mediaan, 10-percentiel en 90-percentiel en de trend en p waarde van de trend van PCB52 (ug/kg) van het zwevende stof van de Westerschelde en de monding berekend op alle beschikbare data vanaf 1996.</caption>
<thead>
<tr class="header">
<th align="center">Station</th>
<th align="center">Mediaan</th>
<th align="center">90-perc</th>
<th align="center">10-perc</th>
<th align="center">Trend</th>
<th align="center">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Schaar van Ouden Doel</td>
<td align="center">4.7</td>
<td align="center">6.8</td>
<td align="center">2.48</td>
<td align="center">-0.174</td>
<td align="center">0.000</td>
</tr>
<tr class="even">
<td align="center">Vlissingen boei SSVH</td>
<td align="center">0.6</td>
<td align="center">0.8</td>
<td align="center">0.25</td>
<td align="center">-0.015</td>
<td align="center">0.002</td>
</tr>
</tbody>
</table>
<div class="figure" style="text-align: center"><span id="fig:zwevendPCB52"></span>
<img src="_main_files/figure-html/zwevendPCB52-1.png" alt="Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van PCB52 voor beide stations." width="85%" />
<p class="caption">
Figuur 5.30: Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van PCB52 voor beide stations.
</p>
</div>
</div>
<div id="zwevend-PCB118" class="section level3" number="5.5.6">
<h3><span class="header-section-number">5.5.6</span> PCB118</h3>
<p>Figuur <a href="zwevend-stof.html#fig:zwevendPCB118">5.31</a> toont het jaargemiddelde PCB118 per station voor de periode vanaf 1996 t/m 2019, samen met de laagste en de hoogste gemeten waarde per jaar. Daarnaast zijn in Tabel <a href="zwevend-stof.html#tab:zwevendPCB118Tab">5.27</a> de gemiddelde, minimale en maximale waardes per station weergegeven. Voor beide stations constateren we een afnemende lineaire trend rond de 0,04 tot 0,29 <span class="math inline">\(\mu\)</span>g/kg per jaar. Voor station Vlissingen de trend een hogere correlatie coëfficiënt.</p>
<table>
<caption><span id="tab:zwevendPCB118Tab">Tabel 5.27: </span>Jaarlijks mediaan, 10-percentiel en 90-percentiel en de trend en p waarde van de trend van PCB118 (ug/kg) van het zwevende stof van de Westerschelde en de monding berekend op alle beschikbare data vanaf 1996.</caption>
<thead>
<tr class="header">
<th align="center">Station</th>
<th align="center">Mediaan</th>
<th align="center">90-perc</th>
<th align="center">10-perc</th>
<th align="center">Trend</th>
<th align="center">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Schaar van Ouden Doel</td>
<td align="center">8.0</td>
<td align="center">10.0</td>
<td align="center">4.000</td>
<td align="center">-0.213</td>
<td align="center">0</td>
</tr>
<tr class="even">
<td align="center">Vlissingen boei SSVH</td>
<td align="center">1.2</td>
<td align="center">1.7</td>
<td align="center">0.809</td>
<td align="center">-0.048</td>
<td align="center">0</td>
</tr>
</tbody>
</table>
<div class="figure" style="text-align: center"><span id="fig:zwevendPCB118"></span>
<img src="_main_files/figure-html/zwevendPCB118-1.png" alt="Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van PCB118 voor beide stations." width="85%" />
<p class="caption">
Figuur 5.31: Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van PCB118 voor beide stations.
</p>
</div>
</div>
<div id="zwevend-PCB28" class="section level3" number="5.5.7">
<h3><span class="header-section-number">5.5.7</span> PCB28</h3>
<p>Figuur <a href="zwevend-stof.html#fig:zwevendPCB28">5.32</a> toont het jaargemiddelde PCB28 per station voor de periode vanaf 1996 t/m 2019, samen met de laagste en de hoogste gemeten waarde per jaar. Daarnaast zijn in Tabel <a href="zwevend-stof.html#tab:zwevendPCB28Tab">5.28</a> de gemiddelde, minimale en maximale waardes per station weergegeven. Voor beide stations neemt de hoeveelheid PCB28 af. Voor Schaar van Ouden Doel is de trend hoger vergeleken met Vlissingen. De hoge waarde in 2017 bij Schaar van Ouden Doel lijkt een uitschieter. Het is de vraag of deze meegenomen moet worden in de berekening van het gemiddelde.</p>
<table>
<caption><span id="tab:zwevendPCB28Tab">Tabel 5.28: </span>Jaarlijks mediaan, 10-percentiel en 90-percentiel en de trend en p waarde van de trend van PCB28 (ug/kg) van het zwevende stof van de Westerschelde en de monding berekend op alle beschikbare data vanaf 1996.</caption>
<thead>
<tr class="header">
<th align="center">Station</th>
<th align="center">Mediaan</th>
<th align="center">90-perc</th>
<th align="center">10-perc</th>
<th align="center">Trend</th>
<th align="center">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Schaar van Ouden Doel</td>
<td align="center">2.3</td>
<td align="center">3.50</td>
<td align="center">1.000</td>
<td align="center">-0.053</td>
<td align="center">0.033</td>
</tr>
<tr class="even">
<td align="center">Vlissingen boei SSVH</td>
<td align="center">0.7</td>
<td align="center">1.22</td>
<td align="center">0.544</td>
<td align="center">-0.020</td>
<td align="center">0.002</td>
</tr>
</tbody>
</table>
<div class="figure" style="text-align: center"><span id="fig:zwevendPCB28"></span>
<img src="_main_files/figure-html/zwevendPCB28-1.png" alt="Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van PCB28 voor beide stations." width="85%" />
<p class="caption">
Figuur 5.32: Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van PCB28 voor beide stations.
</p>
</div>
</div>
</div>
<div id="zwevend-overig" class="section level2" number="5.6">
<h2><span class="header-section-number">5.6</span> Overige stoffen</h2>
<p>In deze paragraaf presenteren we de volgende overige stoffen in zwevende stof:</p>
<ul>
<li>Dieldrin (Figuur <a href="zwevend-stof.html#fig:zwevendDieldrin">5.33</a>)</li>
<li>Hexachloorbenzeen (Figuur <a href="zwevend-stof.html#fig:zwevendHexachloorbenzeen">5.34</a>)</li>
<li>Tributyltin (Figuur <a href="zwevend-stof.html#fig:zwevendTributyltin">5.35</a>)</li>
</ul>
<div id="zwevend-dieldrin" class="section level3" number="5.6.1">
<h3><span class="header-section-number">5.6.1</span> Dieldrin</h3>
<p>Figuur <a href="zwevend-stof.html#fig:zwevendDieldrin">5.33</a> toont het jaargemiddelde dieldrin per station voor de periode vanaf 1996 t/m 2019, samen met de laagste en de hoogste gemeten waarde per jaar. Daarnaast zijn in Tabel <a href="zwevend-stof.html#tab:zwevendDieldrinTab">5.29</a> de gemiddelde, minimale en maximale waardes per station weergegeven.</p>
<p>Het gehalte dieldrin wordt alleen bij Schaar van Ouden Doel bepaald en beïnvloed door de detectiegrens van 0,5 mg/l, dit laten de minima duidelijk zien. In werkelijkheid zullen de minima en gemiddelden dus lager zijn. De dalende trend sinds de incidentele piek in 2006 is niet significant. Sinds 2010 volgde uit 40% van de metingen een waarde van 0,5 mg/l. In 2018, net als in 2016 en 2017, volgde uit alle metingen een waarde van 1 mg/l. Hierdoor zijn de gemiddelde, minimale en maximale waarde gelijk. Dit kan er op duiden dat de detectie grens is verschoven of dat de meetapparatuur niet meer functioneert.</p>
<table>
<caption><span id="tab:zwevendDieldrinTab">Tabel 5.29: </span>Jaarlijks mediaan, 10-percentiel en 90-percentiel en de trend en p waarde van de trend van dieldrin (ug/kg) van het zwevende stof van de Westerschelde en de monding berekend op alle beschikbare data vanaf 1996.</caption>
<thead>
<tr class="header">
<th align="center">Station</th>
<th align="center">Mediaan</th>
<th align="center">90-perc</th>
<th align="center">10-perc</th>
<th align="center">Trend</th>
<th align="center">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Schaar van Ouden Doel</td>
<td align="center">0.6</td>
<td align="center">1.8</td>
<td align="center">0.25</td>
<td align="center">-0.039</td>
<td align="center">0.005</td>
</tr>
</tbody>
</table>
<div class="figure" style="text-align: center"><span id="fig:zwevendDieldrin"></span>
<img src="_main_files/figure-html/zwevendDieldrin-1.png" alt="Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Dieldrin voor beide stations." width="85%" />
<p class="caption">
Figuur 5.33: Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Dieldrin voor beide stations.
</p>
</div>
</div>
<div id="zwevend-Hexachloorbenzeen" class="section level3" number="5.6.2">
<h3><span class="header-section-number">5.6.2</span> Hexachloorbenzeen</h3>
<p>Figuur <a href="zwevend-stof.html#fig:zwevendHexachloorbenzeen">5.34</a> toont het jaargemiddelde hexachloorbenzeen per station voor de periode vanaf 1996 t/m 2019, samen met de laagste en de hoogste gemeten waarde per jaar. Daarnaast zijn in Tabel <a href="zwevend-stof.html#tab:zwevendHexachloorbenzeenTab">5.30</a> de gemiddelde, minimale en maximale waardes per station weergegeven.</p>
<p>Bij Vlissingen boei SSVH is het gehalte hexachloorbenzeen zeer laag en wordt steeds de detectiegrens van 0,5 mg/l bereikt, waardoor de minima en gemiddelden worden bepaald. In werkelijkheid zijn de gehaltes dus nog lager. Over de gehele dataset is geen trend te herkennen.</p>
<table>
<caption><span id="tab:zwevendHexachloorbenzeenTab">Tabel 5.30: </span>Jaarlijks mediaan, 10-percentiel en 90-percentiel en de trend en p waarde van de trend van hexachloorbenzeen (ug/kg) van het zwevende stof van de Westerschelde en de monding berekend op alle beschikbare data vanaf 1996.</caption>
<thead>
<tr class="header">
<th align="center">Station</th>
<th align="center">Mediaan</th>
<th align="center">90-perc</th>
<th align="center">10-perc</th>
<th align="center">Trend</th>
<th align="center">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Schaar van Ouden Doel</td>
<td align="center">1.00</td>
<td align="center">1.9</td>
<td align="center">0.50</td>
<td align="center">-0.041</td>
<td align="center">0.001</td>
</tr>
<tr class="even">
<td align="center">Vlissingen boei SSVH</td>
<td align="center">0.25</td>
<td align="center">0.5</td>
<td align="center">0.25</td>
<td align="center">-0.010</td>
<td align="center">0.000</td>
</tr>
</tbody>
</table>
<div class="figure" style="text-align: center"><span id="fig:zwevendHexachloorbenzeen"></span>
<img src="_main_files/figure-html/zwevendHexachloorbenzeen-1.png" alt="Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Hexachloorbenzeen voor beide stations." width="85%" />
<p class="caption">
Figuur 5.34: Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Hexachloorbenzeen voor beide stations.
</p>
</div>
</div>
<div id="zwevend-Tributyltin" class="section level3" number="5.6.3">
<h3><span class="header-section-number">5.6.3</span> Tributyltin</h3>
<p>Figuur <a href="zwevend-stof.html#fig:zwevendTributyltin">5.35</a> toont het jaargemiddelde tributyltin per station voor de periode vanaf 1996 t/m 2019, samen met de laagste en de hoogste gemeten waarde per jaar. Daarnaast zijn in Tabel <a href="zwevend-stof.html#tab:zwevendTributyltinTab">5.31</a> de gemiddelde, minimale en maximale waardes per station weergegeven.</p>
<p>In 2012 worden de waarden van tribultyltin (TBT) bij Schaar van Ouden Doel niet meer uitgedrukt in tin, de oude metingen (wel uitgedrukt in tin) zijn door te vermenigvuldigen met factor 2,444 omgerekend naar tribultyltin. Bij Schaar van Ouden Doel dalen de gehaltes tribultyltin sterk. Bij Vlissingen boei SSVH is een dalende trend aanwezig. De waarden bij Vlissingen boei SSVH zijn lager dan bij Schaar van Ouden Doel. Bij Vlissingen boei SSVH wordt de laatste jaren zelfs de detectiegrens bereikt (3 <span class="math inline">\(\mu\)</span>g/kg). Over de gehele dataset is er een duidelijke dalende trend van -5,2 tot -7,4 <span class="math inline">\(\mu\)</span>g/kg te herkennen die voor beide stations een hoge correlatiecoëfficiënt heeft. Deze daling lijkt wel af te nemen met stabiliserende waardes in de laatste jaren. Voor Vlissingen was in 2017 geen data beschikbaar.</p>
<table>
<caption><span id="tab:zwevendTributyltinTab">Tabel 5.31: </span>Jaarlijks mediaan, 10-percentiel en 90-percentiel en de trend en p waarde van de trend van tributyltin (ug/kg) van het zwevende stof van de Westerschelde en de monding berekend op alle beschikbare data vanaf 1996.</caption>
<thead>
<tr class="header">
<th align="center">Station</th>
<th align="center">Mediaan</th>
<th align="center">90-perc</th>
<th align="center">10-perc</th>
<th align="center">Trend</th>
<th align="center">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Schaar van Ouden Doel</td>
<td align="center">34.4</td>
<td align="center">46.1</td>
<td align="center">26.40</td>
<td align="center">-3.11</td>
<td align="center">0.001</td>
</tr>
<tr class="even">
<td align="center">Vlissingen boei SSVH</td>
<td align="center">15.0</td>
<td align="center">75.0</td>
<td align="center">5.68</td>
<td align="center">-3.68</td>
<td align="center">0.000</td>
</tr>
</tbody>
</table>
<div class="figure" style="text-align: center"><span id="fig:zwevendTributyltin"></span>
<img src="_main_files/figure-html/zwevendTributyltin-1.png" alt="Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Tributyltin voor beide stations." width="85%" />
<p class="caption">
Figuur 5.35: Jaarlijks gemiddelde (groen), minimum (blauw) en maximum (rood) van Tributyltin voor beide stations.
</p>
</div>

<!-- TO DO:
- bijlage referentie
- figuren headers bijwerken met percentiele ipv min-max
- merge fractie en geen fractie parameters tot 1 tijdserie
- Som PCB mist nog data
- Tributyltin heeft 2 parnames voor de complete serie

-->
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="fysisch-oppwater.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="bodem.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
},
"toc_float": {
"collapsed": false,
"smooth_scroll": false
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
